<?php
return [
    'fa-500px'             => ['class' => 'fa-500px', 'name' => '500px', 'code' => 'f26e'],
    'fa-accessible-icon'   => ['class' => 'fa-accessible-icon', 'name' => 'Accessible icon', 'code' => 'f368'],
    'fa-accusoft'          => ['class' => 'fa-accusoft', 'name' => 'Accusoft', 'code' => 'f369'],
    'fa-address-book'      => ['class' => 'fa-address-book', 'name' => 'Address book', 'code' => 'f2b9'],
    'fa-address-card'      => ['class' => 'fa-address-card', 'name' => 'Address card', 'code' => 'f2bb'],
    'fa-adjust'            => ['class' => 'fa-adjust', 'name' => 'Adjust', 'code' => 'f042'],
    'fa-adn'               => ['class' => 'fa-adn', 'name' => 'Adn', 'code' => 'f170'],
    'fa-adversal'          => ['class' => 'fa-adversal', 'name' => 'Adversal', 'code' => 'f36a'],
    'fa-affiliatetheme'    => ['class' => 'fa-affiliatetheme', 'name' => 'Affiliatetheme', 'code' => 'f36b'],
    'fa-algolia'           => ['class' => 'fa-algolia', 'name' => 'Algolia', 'code' => 'f36c'],
    'fa-align-center'      => ['class' => 'fa-align-center', 'name' => 'Align center', 'code' => 'f037'],
    'fa-align-justify'     => ['class' => 'fa-align-justify', 'name' => 'Align justify', 'code' => 'f039'],
    'fa-align-left'        => ['class' => 'fa-align-left', 'name' => 'Align left', 'code' => 'f036'],
    'fa-align-right'       => ['class' => 'fa-align-right', 'name' => 'Align right', 'code' => 'f038'],
    'fa-amazon'            => ['class' => 'fa-amazon', 'name' => 'Amazon', 'code' => 'f270'],
    'fa-amazon-pay'        => ['class' => 'fa-amazon-pay', 'name' => 'Amazon pay', 'code' => 'f42c'],
    'fa-ambulance'         => ['class' => 'fa-ambulance', 'name' => 'Ambulance', 'code' => 'f0f9'],
    'fa-american-sign-language-interpreting' => ['class' => 'fa-american-sign-language-interpreting', 'name' => 'American sign language interpreting', 'code' => 'f2a3'],
    'fa-amilia'            => ['class' => 'fa-amilia', 'name' => 'Amilia', 'code' => 'f36d'],
    'fa-anchor'            => ['class' => 'fa-anchor', 'name' => 'Anchor', 'code' => 'f13d'],
    'fa-android'           => ['class' => 'fa-android', 'name' => 'Android', 'code' => 'f17b'],
    'fa-angellist'         => ['class' => 'fa-angellist', 'name' => 'Angellist', 'code' => 'f209'],
    'fa-angle-double-down' => ['class' => 'fa-angle-double-down', 'name' => 'Angle double down', 'code' => 'f103'],
    'fa-angle-double-left' => ['class' => 'fa-angle-double-left', 'name' => 'Angle double left', 'code' => 'f100'],
    'fa-angle-double-right' => ['class' => 'fa-angle-double-right', 'name' => 'Angle double right', 'code' => 'f101'],
    'fa-angle-double-up'   => ['class' => 'fa-angle-double-up', 'name' => 'Angle double up', 'code' => 'f102'],
    'fa-angle-down'        => ['class' => 'fa-angle-down', 'name' => 'Angle down', 'code' => 'f107'],
    'fa-angle-left'        => ['class' => 'fa-angle-left', 'name' => 'Angle left', 'code' => 'f104'],
    'fa-angle-right'       => ['class' => 'fa-angle-right', 'name' => 'Angle right', 'code' => 'f105'],
    'fa-angle-up'          => ['class' => 'fa-angle-up', 'name' => 'Angle up', 'code' => 'f106'],
    'fa-angrycreative'     => ['class' => 'fa-angrycreative', 'name' => 'Angrycreative', 'code' => 'f36e'],
    'fa-angular'           => ['class' => 'fa-angular', 'name' => 'Angular', 'code' => 'f420'],
    'fa-app-store'         => ['class' => 'fa-app-store', 'name' => 'App store', 'code' => 'f36f'],
    'fa-app-store-ios'     => ['class' => 'fa-app-store-ios', 'name' => 'App store ios', 'code' => 'f370'],
    'fa-apper'             => ['class' => 'fa-apper', 'name' => 'Apper', 'code' => 'f371'],
    'fa-apple'             => ['class' => 'fa-apple', 'name' => 'Apple', 'code' => 'f179'],
    'fa-apple-pay'         => ['class' => 'fa-apple-pay', 'name' => 'Apple pay', 'code' => 'f415'],
    'fa-archive'           => ['class' => 'fa-archive', 'name' => 'Archive', 'code' => 'f187'],
    'fa-arrow-alt-circle-down' => ['class' => 'fa-arrow-alt-circle-down', 'name' => 'Arrow alt circle down', 'code' => 'f358'],
    'fa-arrow-alt-circle-left' => ['class' => 'fa-arrow-alt-circle-left', 'name' => 'Arrow alt circle left', 'code' => 'f359'],
    'fa-arrow-alt-circle-right' => ['class' => 'fa-arrow-alt-circle-right', 'name' => 'Arrow alt circle right', 'code' => 'f35a'],
    'fa-arrow-alt-circle-up' => ['class' => 'fa-arrow-alt-circle-up', 'name' => 'Arrow alt circle up', 'code' => 'f35b'],
    'fa-arrow-circle-down' => ['class' => 'fa-arrow-circle-down', 'name' => 'Arrow circle down', 'code' => 'f0ab'],
    'fa-arrow-circle-left' => ['class' => 'fa-arrow-circle-left', 'name' => 'Arrow circle left', 'code' => 'f0a8'],
    'fa-arrow-circle-right' => ['class' => 'fa-arrow-circle-right', 'name' => 'Arrow circle right', 'code' => 'f0a9'],
    'fa-arrow-circle-up'   => ['class' => 'fa-arrow-circle-up', 'name' => 'Arrow circle up', 'code' => 'f0aa'],
    'fa-arrow-down'        => ['class' => 'fa-arrow-down', 'name' => 'Arrow down', 'code' => 'f063'],
    'fa-arrow-left'        => ['class' => 'fa-arrow-left', 'name' => 'Arrow left', 'code' => 'f060'],
    'fa-arrow-right'       => ['class' => 'fa-arrow-right', 'name' => 'Arrow right', 'code' => 'f061'],
    'fa-arrow-up'          => ['class' => 'fa-arrow-up', 'name' => 'Arrow up', 'code' => 'f062'],
    'fa-arrows-alt'        => ['class' => 'fa-arrows-alt', 'name' => 'Arrows alt', 'code' => 'f0b2'],
    'fa-arrows-alt-h'      => ['class' => 'fa-arrows-alt-h', 'name' => 'Arrows alt h', 'code' => 'f337'],
    'fa-arrows-alt-v'      => ['class' => 'fa-arrows-alt-v', 'name' => 'Arrows alt v', 'code' => 'f338'],
    'fa-assistive-listening-systems' => ['class' => 'fa-assistive-listening-systems', 'name' => 'Assistive listening systems', 'code' => 'f2a2'],
    'fa-asterisk'          => ['class' => 'fa-asterisk', 'name' => 'Asterisk', 'code' => 'f069'],
    'fa-asymmetrik'        => ['class' => 'fa-asymmetrik', 'name' => 'Asymmetrik', 'code' => 'f372'],
    'fa-at'                => ['class' => 'fa-at', 'name' => 'At', 'code' => 'f1fa'],
    'fa-audible'           => ['class' => 'fa-audible', 'name' => 'Audible', 'code' => 'f373'],
    'fa-audio-description' => ['class' => 'fa-audio-description', 'name' => 'Audio description', 'code' => 'f29e'],
    'fa-autoprefixer'      => ['class' => 'fa-autoprefixer', 'name' => 'Autoprefixer', 'code' => 'f41c'],
    'fa-avianex'           => ['class' => 'fa-avianex', 'name' => 'Avianex', 'code' => 'f374'],
    'fa-aviato'            => ['class' => 'fa-aviato', 'name' => 'Aviato', 'code' => 'f421'],
    'fa-aws'               => ['class' => 'fa-aws', 'name' => 'Aws', 'code' => 'f375'],
    'fa-backward'          => ['class' => 'fa-backward', 'name' => 'Backward', 'code' => 'f04a'],
    'fa-balance-scale'     => ['class' => 'fa-balance-scale', 'name' => 'Balance scale', 'code' => 'f24e'],
    'fa-ban'               => ['class' => 'fa-ban', 'name' => 'Ban', 'code' => 'f05e'],
    'fa-band-aid'          => ['class' => 'fa-band-aid', 'name' => 'Band aid', 'code' => 'f462'],
    'fa-bandcamp'          => ['class' => 'fa-bandcamp', 'name' => 'Bandcamp', 'code' => 'f2d5'],
    'fa-barcode'           => ['class' => 'fa-barcode', 'name' => 'Barcode', 'code' => 'f02a'],
    'fa-bars'              => ['class' => 'fa-bars', 'name' => 'Bars', 'code' => 'f0c9'],
    'fa-baseball-ball'     => ['class' => 'fa-baseball-ball', 'name' => 'Baseball ball', 'code' => 'f433'],
    'fa-basketball-ball'   => ['class' => 'fa-basketball-ball', 'name' => 'Basketball ball', 'code' => 'f434'],
    'fa-bath'              => ['class' => 'fa-bath', 'name' => 'Bath', 'code' => 'f2cd'],
    'fa-battery-empty'     => ['class' => 'fa-battery-empty', 'name' => 'Battery empty', 'code' => 'f244'],
    'fa-battery-full'      => ['class' => 'fa-battery-full', 'name' => 'Battery full', 'code' => 'f240'],
    'fa-battery-half'      => ['class' => 'fa-battery-half', 'name' => 'Battery half', 'code' => 'f242'],
    'fa-battery-quarter'   => ['class' => 'fa-battery-quarter', 'name' => 'Battery quarter', 'code' => 'f243'],
    'fa-battery-three-quarters' => ['class' => 'fa-battery-three-quarters', 'name' => 'Battery three quarters', 'code' => 'f241'],
    'fa-bed'               => ['class' => 'fa-bed', 'name' => 'Bed', 'code' => 'f236'],
    'fa-beer'              => ['class' => 'fa-beer', 'name' => 'Beer', 'code' => 'f0fc'],
    'fa-behance'           => ['class' => 'fa-behance', 'name' => 'Behance', 'code' => 'f1b4'],
    'fa-behance-square'    => ['class' => 'fa-behance-square', 'name' => 'Behance square', 'code' => 'f1b5'],
    'fa-bell'              => ['class' => 'fa-bell', 'name' => 'Bell', 'code' => 'f0f3'],
    'fa-bell-slash'        => ['class' => 'fa-bell-slash', 'name' => 'Bell slash', 'code' => 'f1f6'],
    'fa-bicycle'           => ['class' => 'fa-bicycle', 'name' => 'Bicycle', 'code' => 'f206'],
    'fa-bimobject'         => ['class' => 'fa-bimobject', 'name' => 'Bimobject', 'code' => 'f378'],
    'fa-binoculars'        => ['class' => 'fa-binoculars', 'name' => 'Binoculars', 'code' => 'f1e5'],
    'fa-birthday-cake'     => ['class' => 'fa-birthday-cake', 'name' => 'Birthday cake', 'code' => 'f1fd'],
    'fa-bitbucket'         => ['class' => 'fa-bitbucket', 'name' => 'Bitbucket', 'code' => 'f171'],
    'fa-bitcoin'           => ['class' => 'fa-bitcoin', 'name' => 'Bitcoin', 'code' => 'f379'],
    'fa-bity'              => ['class' => 'fa-bity', 'name' => 'Bity', 'code' => 'f37a'],
    'fa-black-tie'         => ['class' => 'fa-black-tie', 'name' => 'Black tie', 'code' => 'f27e'],
    'fa-blackberry'        => ['class' => 'fa-blackberry', 'name' => 'Blackberry', 'code' => 'f37b'],
    'fa-blind'             => ['class' => 'fa-blind', 'name' => 'Blind', 'code' => 'f29d'],
    'fa-blogger'           => ['class' => 'fa-blogger', 'name' => 'Blogger', 'code' => 'f37c'],
    'fa-blogger-b'         => ['class' => 'fa-blogger-b', 'name' => 'Blogger b', 'code' => 'f37d'],
    'fa-bluetooth'         => ['class' => 'fa-bluetooth', 'name' => 'Bluetooth', 'code' => 'f293'],
    'fa-bluetooth-b'       => ['class' => 'fa-bluetooth-b', 'name' => 'Bluetooth b', 'code' => 'f294'],
    'fa-bold'              => ['class' => 'fa-bold', 'name' => 'Bold', 'code' => 'f032'],
    'fa-bolt'              => ['class' => 'fa-bolt', 'name' => 'Bolt', 'code' => 'f0e7'],
    'fa-bomb'              => ['class' => 'fa-bomb', 'name' => 'Bomb', 'code' => 'f1e2'],
    'fa-book'              => ['class' => 'fa-book', 'name' => 'Book', 'code' => 'f02d'],
    'fa-bookmark'          => ['class' => 'fa-bookmark', 'name' => 'Bookmark', 'code' => 'f02e'],
    'fa-bowling-ball'      => ['class' => 'fa-bowling-ball', 'name' => 'Bowling ball', 'code' => 'f436'],
    'fa-box'               => ['class' => 'fa-box', 'name' => 'Box', 'code' => 'f466'],
    'fa-boxes'             => ['class' => 'fa-boxes', 'name' => 'Boxes', 'code' => 'f468'],
    'fa-braille'           => ['class' => 'fa-braille', 'name' => 'Braille', 'code' => 'f2a1'],
    'fa-briefcase'         => ['class' => 'fa-briefcase', 'name' => 'Briefcase', 'code' => 'f0b1'],
    'fa-btc'               => ['class' => 'fa-btc', 'name' => 'Btc', 'code' => 'f15a'],
    'fa-bug'               => ['class' => 'fa-bug', 'name' => 'Bug', 'code' => 'f188'],
    'fa-building'          => ['class' => 'fa-building', 'name' => 'Building', 'code' => 'f1ad'],
    'fa-bullhorn'          => ['class' => 'fa-bullhorn', 'name' => 'Bullhorn', 'code' => 'f0a1'],
    'fa-bullseye'          => ['class' => 'fa-bullseye', 'name' => 'Bullseye', 'code' => 'f140'],
    'fa-buromobelexperte'  => ['class' => 'fa-buromobelexperte', 'name' => 'Buromobelexperte', 'code' => 'f37f'],
    'fa-bus'               => ['class' => 'fa-bus', 'name' => 'Bus', 'code' => 'f207'],
    'fa-buysellads'        => ['class' => 'fa-buysellads', 'name' => 'Buysellads', 'code' => 'f20d'],
    'fa-calculator'        => ['class' => 'fa-calculator', 'name' => 'Calculator', 'code' => 'f1ec'],
    'fa-calendar'          => ['class' => 'fa-calendar', 'name' => 'Calendar', 'code' => 'f133'],
    'fa-calendar-alt'      => ['class' => 'fa-calendar-alt', 'name' => 'Calendar alt', 'code' => 'f073'],
    'fa-calendar-check'    => ['class' => 'fa-calendar-check', 'name' => 'Calendar check', 'code' => 'f274'],
    'fa-calendar-minus'    => ['class' => 'fa-calendar-minus', 'name' => 'Calendar minus', 'code' => 'f272'],
    'fa-calendar-plus'     => ['class' => 'fa-calendar-plus', 'name' => 'Calendar plus', 'code' => 'f271'],
    'fa-calendar-times'    => ['class' => 'fa-calendar-times', 'name' => 'Calendar times', 'code' => 'f273'],
    'fa-camera'            => ['class' => 'fa-camera', 'name' => 'Camera', 'code' => 'f030'],
    'fa-camera-retro'      => ['class' => 'fa-camera-retro', 'name' => 'Camera retro', 'code' => 'f083'],
    'fa-car'               => ['class' => 'fa-car', 'name' => 'Car', 'code' => 'f1b9'],
    'fa-caret-down'        => ['class' => 'fa-caret-down', 'name' => 'Caret down', 'code' => 'f0d7'],
    'fa-caret-left'        => ['class' => 'fa-caret-left', 'name' => 'Caret left', 'code' => 'f0d9'],
    'fa-caret-right'       => ['class' => 'fa-caret-right', 'name' => 'Caret right', 'code' => 'f0da'],
    'fa-caret-square-down' => ['class' => 'fa-caret-square-down', 'name' => 'Caret square down', 'code' => 'f150'],
    'fa-caret-square-left' => ['class' => 'fa-caret-square-left', 'name' => 'Caret square left', 'code' => 'f191'],
    'fa-caret-square-right' => ['class' => 'fa-caret-square-right', 'name' => 'Caret square right', 'code' => 'f152'],
    'fa-caret-square-up'   => ['class' => 'fa-caret-square-up', 'name' => 'Caret square up', 'code' => 'f151'],
    'fa-caret-up'          => ['class' => 'fa-caret-up', 'name' => 'Caret up', 'code' => 'f0d8'],
    'fa-cart-arrow-down'   => ['class' => 'fa-cart-arrow-down', 'name' => 'Cart arrow down', 'code' => 'f218'],
    'fa-cart-plus'         => ['class' => 'fa-cart-plus', 'name' => 'Cart plus', 'code' => 'f217'],
    'fa-cc-amazon-pay'     => ['class' => 'fa-cc-amazon-pay', 'name' => 'Cc amazon pay', 'code' => 'f42d'],
    'fa-cc-amex'           => ['class' => 'fa-cc-amex', 'name' => 'Cc amex', 'code' => 'f1f3'],
    'fa-cc-apple-pay'      => ['class' => 'fa-cc-apple-pay', 'name' => 'Cc apple pay', 'code' => 'f416'],
    'fa-cc-diners-club'    => ['class' => 'fa-cc-diners-club', 'name' => 'Cc diners club', 'code' => 'f24c'],
    'fa-cc-discover'       => ['class' => 'fa-cc-discover', 'name' => 'Cc discover', 'code' => 'f1f2'],
    'fa-cc-jcb'            => ['class' => 'fa-cc-jcb', 'name' => 'Cc jcb', 'code' => 'f24b'],
    'fa-cc-mastercard'     => ['class' => 'fa-cc-mastercard', 'name' => 'Cc mastercard', 'code' => 'f1f1'],
    'fa-cc-paypal'         => ['class' => 'fa-cc-paypal', 'name' => 'Cc paypal', 'code' => 'f1f4'],
    'fa-cc-stripe'         => ['class' => 'fa-cc-stripe', 'name' => 'Cc stripe', 'code' => 'f1f5'],
    'fa-cc-visa'           => ['class' => 'fa-cc-visa', 'name' => 'Cc visa', 'code' => 'f1f0'],
    'fa-centercode'        => ['class' => 'fa-centercode', 'name' => 'Centercode', 'code' => 'f380'],
    'fa-certificate'       => ['class' => 'fa-certificate', 'name' => 'Certificate', 'code' => 'f0a3'],
    'fa-chart-area'        => ['class' => 'fa-chart-area', 'name' => 'Chart area', 'code' => 'f1fe'],
    'fa-chart-bar'         => ['class' => 'fa-chart-bar', 'name' => 'Chart bar', 'code' => 'f080'],
    'fa-chart-line'        => ['class' => 'fa-chart-line', 'name' => 'Chart line', 'code' => 'f201'],
    'fa-chart-pie'         => ['class' => 'fa-chart-pie', 'name' => 'Chart pie', 'code' => 'f200'],
    'fa-check'             => ['class' => 'fa-check', 'name' => 'Check', 'code' => 'f00c'],
    'fa-check-circle'      => ['class' => 'fa-check-circle', 'name' => 'Check circle', 'code' => 'f058'],
    'fa-check-square'      => ['class' => 'fa-check-square', 'name' => 'Check square', 'code' => 'f14a'],
    'fa-chess'             => ['class' => 'fa-chess', 'name' => 'Chess', 'code' => 'f439'],
    'fa-chess-bishop'      => ['class' => 'fa-chess-bishop', 'name' => 'Chess bishop', 'code' => 'f43a'],
    'fa-chess-board'       => ['class' => 'fa-chess-board', 'name' => 'Chess board', 'code' => 'f43c'],
    'fa-chess-king'        => ['class' => 'fa-chess-king', 'name' => 'Chess king', 'code' => 'f43f'],
    'fa-chess-knight'      => ['class' => 'fa-chess-knight', 'name' => 'Chess knight', 'code' => 'f441'],
    'fa-chess-pawn'        => ['class' => 'fa-chess-pawn', 'name' => 'Chess pawn', 'code' => 'f443'],
    'fa-chess-queen'       => ['class' => 'fa-chess-queen', 'name' => 'Chess queen', 'code' => 'f445'],
    'fa-chess-rook'        => ['class' => 'fa-chess-rook', 'name' => 'Chess rook', 'code' => 'f447'],
    'fa-chevron-circle-down' => ['class' => 'fa-chevron-circle-down', 'name' => 'Chevron circle down', 'code' => 'f13a'],
    'fa-chevron-circle-left' => ['class' => 'fa-chevron-circle-left', 'name' => 'Chevron circle left', 'code' => 'f137'],
    'fa-chevron-circle-right' => ['class' => 'fa-chevron-circle-right', 'name' => 'Chevron circle right', 'code' => 'f138'],
    'fa-chevron-circle-up' => ['class' => 'fa-chevron-circle-up', 'name' => 'Chevron circle up', 'code' => 'f139'],
    'fa-chevron-down'      => ['class' => 'fa-chevron-down', 'name' => 'Chevron down', 'code' => 'f078'],
    'fa-chevron-left'      => ['class' => 'fa-chevron-left', 'name' => 'Chevron left', 'code' => 'f053'],
    'fa-chevron-right'     => ['class' => 'fa-chevron-right', 'name' => 'Chevron right', 'code' => 'f054'],
    'fa-chevron-up'        => ['class' => 'fa-chevron-up', 'name' => 'Chevron up', 'code' => 'f077'],
    'fa-child'             => ['class' => 'fa-child', 'name' => 'Child', 'code' => 'f1ae'],
    'fa-chrome'            => ['class' => 'fa-chrome', 'name' => 'Chrome', 'code' => 'f268'],
    'fa-circle'            => ['class' => 'fa-circle', 'name' => 'Circle', 'code' => 'f111'],
    'fa-circle-notch'      => ['class' => 'fa-circle-notch', 'name' => 'Circle notch', 'code' => 'f1ce'],
    'fa-clipboard'         => ['class' => 'fa-clipboard', 'name' => 'Clipboard', 'code' => 'f328'],
    'fa-clipboard-check'   => ['class' => 'fa-clipboard-check', 'name' => 'Clipboard check', 'code' => 'f46c'],
    'fa-clipboard-list'    => ['class' => 'fa-clipboard-list', 'name' => 'Clipboard list', 'code' => 'f46d'],
    'fa-clock'             => ['class' => 'fa-clock', 'name' => 'Clock', 'code' => 'f017'],
    'fa-clone'             => ['class' => 'fa-clone', 'name' => 'Clone', 'code' => 'f24d'],
    'fa-closed-captioning' => ['class' => 'fa-closed-captioning', 'name' => 'Closed captioning', 'code' => 'f20a'],
    'fa-cloud'             => ['class' => 'fa-cloud', 'name' => 'Cloud', 'code' => 'f0c2'],
    'fa-cloud-download-alt' => ['class' => 'fa-cloud-download-alt', 'name' => 'Cloud download alt', 'code' => 'f381'],
    'fa-cloud-upload-alt'  => ['class' => 'fa-cloud-upload-alt', 'name' => 'Cloud upload alt', 'code' => 'f382'],
    'fa-cloudscale'        => ['class' => 'fa-cloudscale', 'name' => 'Cloudscale', 'code' => 'f383'],
    'fa-cloudsmith'        => ['class' => 'fa-cloudsmith', 'name' => 'Cloudsmith', 'code' => 'f384'],
    'fa-cloudversify'      => ['class' => 'fa-cloudversify', 'name' => 'Cloudversify', 'code' => 'f385'],
    'fa-code'              => ['class' => 'fa-code', 'name' => 'Code', 'code' => 'f121'],
    'fa-code-branch'       => ['class' => 'fa-code-branch', 'name' => 'Code branch', 'code' => 'f126'],
    'fa-codepen'           => ['class' => 'fa-codepen', 'name' => 'Codepen', 'code' => 'f1cb'],
    'fa-codiepie'          => ['class' => 'fa-codiepie', 'name' => 'Codiepie', 'code' => 'f284'],
    'fa-coffee'            => ['class' => 'fa-coffee', 'name' => 'Coffee', 'code' => 'f0f4'],
    'fa-cog'               => ['class' => 'fa-cog', 'name' => 'Cog', 'code' => 'f013'],
    'fa-cogs'              => ['class' => 'fa-cogs', 'name' => 'Cogs', 'code' => 'f085'],
    'fa-columns'           => ['class' => 'fa-columns', 'name' => 'Columns', 'code' => 'f0db'],
    'fa-comment'           => ['class' => 'fa-comment', 'name' => 'Comment', 'code' => 'f075'],
    'fa-comment-alt'       => ['class' => 'fa-comment-alt', 'name' => 'Comment alt', 'code' => 'f27a'],
    'fa-comments'          => ['class' => 'fa-comments', 'name' => 'Comments', 'code' => 'f086'],
    'fa-compass'           => ['class' => 'fa-compass', 'name' => 'Compass', 'code' => 'f14e'],
    'fa-compress'          => ['class' => 'fa-compress', 'name' => 'Compress', 'code' => 'f066'],
    'fa-connectdevelop'    => ['class' => 'fa-connectdevelop', 'name' => 'Connectdevelop', 'code' => 'f20e'],
    'fa-contao'            => ['class' => 'fa-contao', 'name' => 'Contao', 'code' => 'f26d'],
    'fa-copy'              => ['class' => 'fa-copy', 'name' => 'Copy', 'code' => 'f0c5'],
    'fa-copyright'         => ['class' => 'fa-copyright', 'name' => 'Copyright', 'code' => 'f1f9'],
    'fa-cpanel'            => ['class' => 'fa-cpanel', 'name' => 'Cpanel', 'code' => 'f388'],
    'fa-creative-commons'  => ['class' => 'fa-creative-commons', 'name' => 'Creative commons', 'code' => 'f25e'],
    'fa-credit-card'       => ['class' => 'fa-credit-card', 'name' => 'Credit card', 'code' => 'f09d'],
    'fa-crop'              => ['class' => 'fa-crop', 'name' => 'Crop', 'code' => 'f125'],
    'fa-crosshairs'        => ['class' => 'fa-crosshairs', 'name' => 'Crosshairs', 'code' => 'f05b'],
    'fa-css3'              => ['class' => 'fa-css3', 'name' => 'Css3', 'code' => 'f13c'],
    'fa-css3-alt'          => ['class' => 'fa-css3-alt', 'name' => 'Css3 alt', 'code' => 'f38b'],
    'fa-cube'              => ['class' => 'fa-cube', 'name' => 'Cube', 'code' => 'f1b2'],
    'fa-cubes'             => ['class' => 'fa-cubes', 'name' => 'Cubes', 'code' => 'f1b3'],
    'fa-cut'               => ['class' => 'fa-cut', 'name' => 'Cut', 'code' => 'f0c4'],
    'fa-cuttlefish'        => ['class' => 'fa-cuttlefish', 'name' => 'Cuttlefish', 'code' => 'f38c'],
    'fa-d-and-d'           => ['class' => 'fa-d-and-d', 'name' => 'D and d', 'code' => 'f38d'],
    'fa-dashcube'          => ['class' => 'fa-dashcube', 'name' => 'Dashcube', 'code' => 'f210'],
    'fa-database'          => ['class' => 'fa-database', 'name' => 'Database', 'code' => 'f1c0'],
    'fa-deaf'              => ['class' => 'fa-deaf', 'name' => 'Deaf', 'code' => 'f2a4'],
    'fa-delicious'         => ['class' => 'fa-delicious', 'name' => 'Delicious', 'code' => 'f1a5'],
    'fa-deploydog'         => ['class' => 'fa-deploydog', 'name' => 'Deploydog', 'code' => 'f38e'],
    'fa-deskpro'           => ['class' => 'fa-deskpro', 'name' => 'Deskpro', 'code' => 'f38f'],
    'fa-desktop'           => ['class' => 'fa-desktop', 'name' => 'Desktop', 'code' => 'f108'],
    'fa-deviantart'        => ['class' => 'fa-deviantart', 'name' => 'Deviantart', 'code' => 'f1bd'],
    'fa-digg'              => ['class' => 'fa-digg', 'name' => 'Digg', 'code' => 'f1a6'],
    'fa-digital-ocean'     => ['class' => 'fa-digital-ocean', 'name' => 'Digital ocean', 'code' => 'f391'],
    'fa-discord'           => ['class' => 'fa-discord', 'name' => 'Discord', 'code' => 'f392'],
    'fa-discourse'         => ['class' => 'fa-discourse', 'name' => 'Discourse', 'code' => 'f393'],
    'fa-dna'               => ['class' => 'fa-dna', 'name' => 'Dna', 'code' => 'f471'],
    'fa-dochub'            => ['class' => 'fa-dochub', 'name' => 'Dochub', 'code' => 'f394'],
    'fa-docker'            => ['class' => 'fa-docker', 'name' => 'Docker', 'code' => 'f395'],
    'fa-dollar-sign'       => ['class' => 'fa-dollar-sign', 'name' => 'Dollar sign', 'code' => 'f155'],
    'fa-dolly'             => ['class' => 'fa-dolly', 'name' => 'Dolly', 'code' => 'f472'],
    'fa-dolly-flatbed'     => ['class' => 'fa-dolly-flatbed', 'name' => 'Dolly flatbed', 'code' => 'f474'],
    'fa-dot-circle'        => ['class' => 'fa-dot-circle', 'name' => 'Dot circle', 'code' => 'f192'],
    'fa-download'          => ['class' => 'fa-download', 'name' => 'Download', 'code' => 'f019'],
    'fa-draft2digital'     => ['class' => 'fa-draft2digital', 'name' => 'Draft2digital', 'code' => 'f396'],
    'fa-dribbble'          => ['class' => 'fa-dribbble', 'name' => 'Dribbble', 'code' => 'f17d'],
    'fa-dribbble-square'   => ['class' => 'fa-dribbble-square', 'name' => 'Dribbble square', 'code' => 'f397'],
    'fa-dropbox'           => ['class' => 'fa-dropbox', 'name' => 'Dropbox', 'code' => 'f16b'],
    'fa-drupal'            => ['class' => 'fa-drupal', 'name' => 'Drupal', 'code' => 'f1a9'],
    'fa-dyalog'            => ['class' => 'fa-dyalog', 'name' => 'Dyalog', 'code' => 'f399'],
    'fa-earlybirds'        => ['class' => 'fa-earlybirds', 'name' => 'Earlybirds', 'code' => 'f39a'],
    'fa-edge'              => ['class' => 'fa-edge', 'name' => 'Edge', 'code' => 'f282'],
    'fa-edit'              => ['class' => 'fa-edit', 'name' => 'Edit', 'code' => 'f044'],
    'fa-eject'             => ['class' => 'fa-eject', 'name' => 'Eject', 'code' => 'f052'],
    'fa-elementor'         => ['class' => 'fa-elementor', 'name' => 'Elementor', 'code' => 'f430'],
    'fa-ellipsis-h'        => ['class' => 'fa-ellipsis-h', 'name' => 'Ellipsis h', 'code' => 'f141'],
    'fa-ellipsis-v'        => ['class' => 'fa-ellipsis-v', 'name' => 'Ellipsis v', 'code' => 'f142'],
    'fa-ember'             => ['class' => 'fa-ember', 'name' => 'Ember', 'code' => 'f423'],
    'fa-empire'            => ['class' => 'fa-empire', 'name' => 'Empire', 'code' => 'f1d1'],
    'fa-envelope'          => ['class' => 'fa-envelope', 'name' => 'Envelope', 'code' => 'f0e0'],
    'fa-envelope-open'     => ['class' => 'fa-envelope-open', 'name' => 'Envelope open', 'code' => 'f2b6'],
    'fa-envelope-square'   => ['class' => 'fa-envelope-square', 'name' => 'Envelope square', 'code' => 'f199'],
    'fa-envira'            => ['class' => 'fa-envira', 'name' => 'Envira', 'code' => 'f299'],
    'fa-eraser'            => ['class' => 'fa-eraser', 'name' => 'Eraser', 'code' => 'f12d'],
    'fa-erlang'            => ['class' => 'fa-erlang', 'name' => 'Erlang', 'code' => 'f39d'],
    'fa-ethereum'          => ['class' => 'fa-ethereum', 'name' => 'Ethereum', 'code' => 'f42e'],
    'fa-etsy'              => ['class' => 'fa-etsy', 'name' => 'Etsy', 'code' => 'f2d7'],
    'fa-euro-sign'         => ['class' => 'fa-euro-sign', 'name' => 'Euro sign', 'code' => 'f153'],
    'fa-exchange-alt'      => ['class' => 'fa-exchange-alt', 'name' => 'Exchange alt', 'code' => 'f362'],
    'fa-exclamation'       => ['class' => 'fa-exclamation', 'name' => 'Exclamation', 'code' => 'f12a'],
    'fa-exclamation-circle' => ['class' => 'fa-exclamation-circle', 'name' => 'Exclamation circle', 'code' => 'f06a'],
    'fa-exclamation-triangle' => ['class' => 'fa-exclamation-triangle', 'name' => 'Exclamation triangle', 'code' => 'f071'],
    'fa-expand'            => ['class' => 'fa-expand', 'name' => 'Expand', 'code' => 'f065'],
    'fa-expand-arrows-alt' => ['class' => 'fa-expand-arrows-alt', 'name' => 'Expand arrows alt', 'code' => 'f31e'],
    'fa-expeditedssl'      => ['class' => 'fa-expeditedssl', 'name' => 'Expeditedssl', 'code' => 'f23e'],
    'fa-external-link-alt' => ['class' => 'fa-external-link-alt', 'name' => 'External link alt', 'code' => 'f35d'],
    'fa-external-link-square-alt' => ['class' => 'fa-external-link-square-alt', 'name' => 'External link square alt', 'code' => 'f360'],
    'fa-eye'               => ['class' => 'fa-eye', 'name' => 'Eye', 'code' => 'f06e'],
    'fa-eye-dropper'       => ['class' => 'fa-eye-dropper', 'name' => 'Eye dropper', 'code' => 'f1fb'],
    'fa-eye-slash'         => ['class' => 'fa-eye-slash', 'name' => 'Eye slash', 'code' => 'f070'],
    'fa-facebook'          => ['class' => 'fa-facebook', 'name' => 'Facebook', 'code' => 'f09a'],
    'fa-facebook-f'        => ['class' => 'fa-facebook-f', 'name' => 'Facebook f', 'code' => 'f39e'],
    'fa-facebook-messenger' => ['class' => 'fa-facebook-messenger', 'name' => 'Facebook messenger', 'code' => 'f39f'],
    'fa-facebook-square'   => ['class' => 'fa-facebook-square', 'name' => 'Facebook square', 'code' => 'f082'],
    'fa-fast-backward'     => ['class' => 'fa-fast-backward', 'name' => 'Fast backward', 'code' => 'f049'],
    'fa-fast-forward'      => ['class' => 'fa-fast-forward', 'name' => 'Fast forward', 'code' => 'f050'],
    'fa-fax'               => ['class' => 'fa-fax', 'name' => 'Fax', 'code' => 'f1ac'],
    'fa-female'            => ['class' => 'fa-female', 'name' => 'Female', 'code' => 'f182'],
    'fa-fighter-jet'       => ['class' => 'fa-fighter-jet', 'name' => 'Fighter jet', 'code' => 'f0fb'],
    'fa-file'              => ['class' => 'fa-file', 'name' => 'File', 'code' => 'f15b'],
    'fa-file-alt'          => ['class' => 'fa-file-alt', 'name' => 'File alt', 'code' => 'f15c'],
    'fa-file-archive'      => ['class' => 'fa-file-archive', 'name' => 'File archive', 'code' => 'f1c6'],
    'fa-file-audio'        => ['class' => 'fa-file-audio', 'name' => 'File audio', 'code' => 'f1c7'],
    'fa-file-code'         => ['class' => 'fa-file-code', 'name' => 'File code', 'code' => 'f1c9'],
    'fa-file-excel'        => ['class' => 'fa-file-excel', 'name' => 'File excel', 'code' => 'f1c3'],
    'fa-file-image'        => ['class' => 'fa-file-image', 'name' => 'File image', 'code' => 'f1c5'],
    'fa-file-pdf'          => ['class' => 'fa-file-pdf', 'name' => 'File pdf', 'code' => 'f1c1'],
    'fa-file-powerpoint'   => ['class' => 'fa-file-powerpoint', 'name' => 'File powerpoint', 'code' => 'f1c4'],
    'fa-file-video'        => ['class' => 'fa-file-video', 'name' => 'File video', 'code' => 'f1c8'],
    'fa-file-word'         => ['class' => 'fa-file-word', 'name' => 'File word', 'code' => 'f1c2'],
    'fa-film'              => ['class' => 'fa-film', 'name' => 'Film', 'code' => 'f008'],
    'fa-filter'            => ['class' => 'fa-filter', 'name' => 'Filter', 'code' => 'f0b0'],
    'fa-fire'              => ['class' => 'fa-fire', 'name' => 'Fire', 'code' => 'f06d'],
    'fa-fire-extinguisher' => ['class' => 'fa-fire-extinguisher', 'name' => 'Fire extinguisher', 'code' => 'f134'],
    'fa-firefox'           => ['class' => 'fa-firefox', 'name' => 'Firefox', 'code' => 'f269'],
    'fa-first-aid'         => ['class' => 'fa-first-aid', 'name' => 'First aid', 'code' => 'f479'],
    'fa-first-order'       => ['class' => 'fa-first-order', 'name' => 'First order', 'code' => 'f2b0'],
    'fa-firstdraft'        => ['class' => 'fa-firstdraft', 'name' => 'Firstdraft', 'code' => 'f3a1'],
    'fa-flag'              => ['class' => 'fa-flag', 'name' => 'Flag', 'code' => 'f024'],
    'fa-flag-checkered'    => ['class' => 'fa-flag-checkered', 'name' => 'Flag checkered', 'code' => 'f11e'],
    'fa-flask'             => ['class' => 'fa-flask', 'name' => 'Flask', 'code' => 'f0c3'],
    'fa-flickr'            => ['class' => 'fa-flickr', 'name' => 'Flickr', 'code' => 'f16e'],
    'fa-flipboard'         => ['class' => 'fa-flipboard', 'name' => 'Flipboard', 'code' => 'f44d'],
    'fa-fly'               => ['class' => 'fa-fly', 'name' => 'Fly', 'code' => 'f417'],
    'fa-folder'            => ['class' => 'fa-folder', 'name' => 'Folder', 'code' => 'f07b'],
    'fa-folder-open'       => ['class' => 'fa-folder-open', 'name' => 'Folder open', 'code' => 'f07c'],
    'fa-font'              => ['class' => 'fa-font', 'name' => 'Font', 'code' => 'f031'],
    'fa-font-awesome'      => ['class' => 'fa-font-awesome', 'name' => 'Font awesome', 'code' => 'f2b4'],
    'fa-font-awesome-alt'  => ['class' => 'fa-font-awesome-alt', 'name' => 'Font awesome alt', 'code' => 'f35c'],
    'fa-font-awesome-flag' => ['class' => 'fa-font-awesome-flag', 'name' => 'Font awesome flag', 'code' => 'f425'],
    'fa-fonticons'         => ['class' => 'fa-fonticons', 'name' => 'Fonticons', 'code' => 'f280'],
    'fa-fonticons-fi'      => ['class' => 'fa-fonticons-fi', 'name' => 'Fonticons fi', 'code' => 'f3a2'],
    'fa-football-ball'     => ['class' => 'fa-football-ball', 'name' => 'Football ball', 'code' => 'f44e'],
    'fa-fort-awesome'      => ['class' => 'fa-fort-awesome', 'name' => 'Fort awesome', 'code' => 'f286'],
    'fa-fort-awesome-alt'  => ['class' => 'fa-fort-awesome-alt', 'name' => 'Fort awesome alt', 'code' => 'f3a3'],
    'fa-forumbee'          => ['class' => 'fa-forumbee', 'name' => 'Forumbee', 'code' => 'f211'],
    'fa-forward'           => ['class' => 'fa-forward', 'name' => 'Forward', 'code' => 'f04e'],
    'fa-foursquare'        => ['class' => 'fa-foursquare', 'name' => 'Foursquare', 'code' => 'f180'],
    'fa-free-code-camp'    => ['class' => 'fa-free-code-camp', 'name' => 'Free code camp', 'code' => 'f2c5'],
    'fa-freebsd'           => ['class' => 'fa-freebsd', 'name' => 'Freebsd', 'code' => 'f3a4'],
    'fa-frown'             => ['class' => 'fa-frown', 'name' => 'Frown', 'code' => 'f119'],
    'fa-futbol'            => ['class' => 'fa-futbol', 'name' => 'Futbol', 'code' => 'f1e3'],
    'fa-gamepad'           => ['class' => 'fa-gamepad', 'name' => 'Gamepad', 'code' => 'f11b'],
    'fa-gavel'             => ['class' => 'fa-gavel', 'name' => 'Gavel', 'code' => 'f0e3'],
    'fa-gem'               => ['class' => 'fa-gem', 'name' => 'Gem', 'code' => 'f3a5'],
    'fa-genderless'        => ['class' => 'fa-genderless', 'name' => 'Genderless', 'code' => 'f22d'],
    'fa-get-pocket'        => ['class' => 'fa-get-pocket', 'name' => 'Get pocket', 'code' => 'f265'],
    'fa-gg'                => ['class' => 'fa-gg', 'name' => 'Gg', 'code' => 'f260'],
    'fa-gg-circle'         => ['class' => 'fa-gg-circle', 'name' => 'Gg circle', 'code' => 'f261'],
    'fa-gift'              => ['class' => 'fa-gift', 'name' => 'Gift', 'code' => 'f06b'],
    'fa-git'               => ['class' => 'fa-git', 'name' => 'Git', 'code' => 'f1d3'],
    'fa-git-square'        => ['class' => 'fa-git-square', 'name' => 'Git square', 'code' => 'f1d2'],
    'fa-github'            => ['class' => 'fa-github', 'name' => 'Github', 'code' => 'f09b'],
    'fa-github-alt'        => ['class' => 'fa-github-alt', 'name' => 'Github alt', 'code' => 'f113'],
    'fa-github-square'     => ['class' => 'fa-github-square', 'name' => 'Github square', 'code' => 'f092'],
    'fa-gitkraken'         => ['class' => 'fa-gitkraken', 'name' => 'Gitkraken', 'code' => 'f3a6'],
    'fa-gitlab'            => ['class' => 'fa-gitlab', 'name' => 'Gitlab', 'code' => 'f296'],
    'fa-gitter'            => ['class' => 'fa-gitter', 'name' => 'Gitter', 'code' => 'f426'],
    'fa-glass-martini'     => ['class' => 'fa-glass-martini', 'name' => 'Glass martini', 'code' => 'f000'],
    'fa-glide'             => ['class' => 'fa-glide', 'name' => 'Glide', 'code' => 'f2a5'],
    'fa-glide-g'           => ['class' => 'fa-glide-g', 'name' => 'Glide g', 'code' => 'f2a6'],
    'fa-globe'             => ['class' => 'fa-globe', 'name' => 'Globe', 'code' => 'f0ac'],
    'fa-gofore'            => ['class' => 'fa-gofore', 'name' => 'Gofore', 'code' => 'f3a7'],
    'fa-golf-ball'         => ['class' => 'fa-golf-ball', 'name' => 'Golf ball', 'code' => 'f450'],
    'fa-goodreads'         => ['class' => 'fa-goodreads', 'name' => 'Goodreads', 'code' => 'f3a8'],
    'fa-goodreads-g'       => ['class' => 'fa-goodreads-g', 'name' => 'Goodreads g', 'code' => 'f3a9'],
    'fa-google'            => ['class' => 'fa-google', 'name' => 'Google', 'code' => 'f1a0'],
    'fa-google-drive'      => ['class' => 'fa-google-drive', 'name' => 'Google drive', 'code' => 'f3aa'],
    'fa-google-play'       => ['class' => 'fa-google-play', 'name' => 'Google play', 'code' => 'f3ab'],
    'fa-google-plus'       => ['class' => 'fa-google-plus', 'name' => 'Google plus', 'code' => 'f2b3'],
    'fa-google-plus-g'     => ['class' => 'fa-google-plus-g', 'name' => 'Google plus g', 'code' => 'f0d5'],
    'fa-google-plus-square' => ['class' => 'fa-google-plus-square', 'name' => 'Google plus square', 'code' => 'f0d4'],
    'fa-google-wallet'     => ['class' => 'fa-google-wallet', 'name' => 'Google wallet', 'code' => 'f1ee'],
    'fa-graduation-cap'    => ['class' => 'fa-graduation-cap', 'name' => 'Graduation cap', 'code' => 'f19d'],
    'fa-gratipay'          => ['class' => 'fa-gratipay', 'name' => 'Gratipay', 'code' => 'f184'],
    'fa-grav'              => ['class' => 'fa-grav', 'name' => 'Grav', 'code' => 'f2d6'],
    'fa-gripfire'          => ['class' => 'fa-gripfire', 'name' => 'Gripfire', 'code' => 'f3ac'],
    'fa-grunt'             => ['class' => 'fa-grunt', 'name' => 'Grunt', 'code' => 'f3ad'],
    'fa-gulp'              => ['class' => 'fa-gulp', 'name' => 'Gulp', 'code' => 'f3ae'],
    'fa-h-square'          => ['class' => 'fa-h-square', 'name' => 'H square', 'code' => 'f0fd'],
    'fa-hacker-news'       => ['class' => 'fa-hacker-news', 'name' => 'Hacker news', 'code' => 'f1d4'],
    'fa-hacker-news-square' => ['class' => 'fa-hacker-news-square', 'name' => 'Hacker news square', 'code' => 'f3af'],
    'fa-hand-lizard'       => ['class' => 'fa-hand-lizard', 'name' => 'Hand lizard', 'code' => 'f258'],
    'fa-hand-paper'        => ['class' => 'fa-hand-paper', 'name' => 'Hand paper', 'code' => 'f256'],
    'fa-hand-peace'        => ['class' => 'fa-hand-peace', 'name' => 'Hand peace', 'code' => 'f25b'],
    'fa-hand-point-down'   => ['class' => 'fa-hand-point-down', 'name' => 'Hand point down', 'code' => 'f0a7'],
    'fa-hand-point-left'   => ['class' => 'fa-hand-point-left', 'name' => 'Hand point left', 'code' => 'f0a5'],
    'fa-hand-point-right'  => ['class' => 'fa-hand-point-right', 'name' => 'Hand point right', 'code' => 'f0a4'],
    'fa-hand-point-up'     => ['class' => 'fa-hand-point-up', 'name' => 'Hand point up', 'code' => 'f0a6'],
    'fa-hand-pointer'      => ['class' => 'fa-hand-pointer', 'name' => 'Hand pointer', 'code' => 'f25a'],
    'fa-hand-rock'         => ['class' => 'fa-hand-rock', 'name' => 'Hand rock', 'code' => 'f255'],
    'fa-hand-scissors'     => ['class' => 'fa-hand-scissors', 'name' => 'Hand scissors', 'code' => 'f257'],
    'fa-hand-spock'        => ['class' => 'fa-hand-spock', 'name' => 'Hand spock', 'code' => 'f259'],
    'fa-handshake'         => ['class' => 'fa-handshake', 'name' => 'Handshake', 'code' => 'f2b5'],
    'fa-hashtag'           => ['class' => 'fa-hashtag', 'name' => 'Hashtag', 'code' => 'f292'],
    'fa-hdd'               => ['class' => 'fa-hdd', 'name' => 'Hdd', 'code' => 'f0a0'],
    'fa-heading'           => ['class' => 'fa-heading', 'name' => 'Heading', 'code' => 'f1dc'],
    'fa-headphones'        => ['class' => 'fa-headphones', 'name' => 'Headphones', 'code' => 'f025'],
    'fa-heart'             => ['class' => 'fa-heart', 'name' => 'Heart', 'code' => 'f004'],
    'fa-heartbeat'         => ['class' => 'fa-heartbeat', 'name' => 'Heartbeat', 'code' => 'f21e'],
    'fa-hips'              => ['class' => 'fa-hips', 'name' => 'Hips', 'code' => 'f452'],
    'fa-hire-a-helper'     => ['class' => 'fa-hire-a-helper', 'name' => 'Hire a helper', 'code' => 'f3b0'],
    'fa-history'           => ['class' => 'fa-history', 'name' => 'History', 'code' => 'f1da'],
    'fa-hockey-puck'       => ['class' => 'fa-hockey-puck', 'name' => 'Hockey puck', 'code' => 'f453'],
    'fa-home'              => ['class' => 'fa-home', 'name' => 'Home', 'code' => 'f015'],
    'fa-hooli'             => ['class' => 'fa-hooli', 'name' => 'Hooli', 'code' => 'f427'],
    'fa-hospital'          => ['class' => 'fa-hospital', 'name' => 'Hospital', 'code' => 'f0f8'],
    'fa-hospital-symbol'   => ['class' => 'fa-hospital-symbol', 'name' => 'Hospital symbol', 'code' => 'f47e'],
    'fa-hotjar'            => ['class' => 'fa-hotjar', 'name' => 'Hotjar', 'code' => 'f3b1'],
    'fa-hourglass'         => ['class' => 'fa-hourglass', 'name' => 'Hourglass', 'code' => 'f254'],
    'fa-hourglass-end'     => ['class' => 'fa-hourglass-end', 'name' => 'Hourglass end', 'code' => 'f253'],
    'fa-hourglass-half'    => ['class' => 'fa-hourglass-half', 'name' => 'Hourglass half', 'code' => 'f252'],
    'fa-hourglass-start'   => ['class' => 'fa-hourglass-start', 'name' => 'Hourglass start', 'code' => 'f251'],
    'fa-houzz'             => ['class' => 'fa-houzz', 'name' => 'Houzz', 'code' => 'f27c'],
    'fa-html5'             => ['class' => 'fa-html5', 'name' => 'Html5', 'code' => 'f13b'],
    'fa-hubspot'           => ['class' => 'fa-hubspot', 'name' => 'Hubspot', 'code' => 'f3b2'],
    'fa-i-cursor'          => ['class' => 'fa-i-cursor', 'name' => 'I cursor', 'code' => 'f246'],
    'fa-id-badge'          => ['class' => 'fa-id-badge', 'name' => 'Id badge', 'code' => 'f2c1'],
    'fa-id-card'           => ['class' => 'fa-id-card', 'name' => 'Id card', 'code' => 'f2c2'],
    'fa-image'             => ['class' => 'fa-image', 'name' => 'Image', 'code' => 'f03e'],
    'fa-images'            => ['class' => 'fa-images', 'name' => 'Images', 'code' => 'f302'],
    'fa-imdb'              => ['class' => 'fa-imdb', 'name' => 'Imdb', 'code' => 'f2d8'],
    'fa-inbox'             => ['class' => 'fa-inbox', 'name' => 'Inbox', 'code' => 'f01c'],
    'fa-indent'            => ['class' => 'fa-indent', 'name' => 'Indent', 'code' => 'f03c'],
    'fa-industry'          => ['class' => 'fa-industry', 'name' => 'Industry', 'code' => 'f275'],
    'fa-info'              => ['class' => 'fa-info', 'name' => 'Info', 'code' => 'f129'],
    'fa-info-circle'       => ['class' => 'fa-info-circle', 'name' => 'Info circle', 'code' => 'f05a'],
    'fa-instagram'         => ['class' => 'fa-instagram', 'name' => 'Instagram', 'code' => 'f16d'],
    'fa-internet-explorer' => ['class' => 'fa-internet-explorer', 'name' => 'Internet explorer', 'code' => 'f26b'],
    'fa-ioxhost'           => ['class' => 'fa-ioxhost', 'name' => 'Ioxhost', 'code' => 'f208'],
    'fa-italic'            => ['class' => 'fa-italic', 'name' => 'Italic', 'code' => 'f033'],
    'fa-itunes'            => ['class' => 'fa-itunes', 'name' => 'Itunes', 'code' => 'f3b4'],
    'fa-itunes-note'       => ['class' => 'fa-itunes-note', 'name' => 'Itunes note', 'code' => 'f3b5'],
    'fa-jenkins'           => ['class' => 'fa-jenkins', 'name' => 'Jenkins', 'code' => 'f3b6'],
    'fa-joget'             => ['class' => 'fa-joget', 'name' => 'Joget', 'code' => 'f3b7'],
    'fa-joomla'            => ['class' => 'fa-joomla', 'name' => 'Joomla', 'code' => 'f1aa'],
    'fa-js'                => ['class' => 'fa-js', 'name' => 'Js', 'code' => 'f3b8'],
    'fa-js-square'         => ['class' => 'fa-js-square', 'name' => 'Js square', 'code' => 'f3b9'],
    'fa-jsfiddle'          => ['class' => 'fa-jsfiddle', 'name' => 'Jsfiddle', 'code' => 'f1cc'],
    'fa-key'               => ['class' => 'fa-key', 'name' => 'Key', 'code' => 'f084'],
    'fa-keyboard'          => ['class' => 'fa-keyboard', 'name' => 'Keyboard', 'code' => 'f11c'],
    'fa-keycdn'            => ['class' => 'fa-keycdn', 'name' => 'Keycdn', 'code' => 'f3ba'],
    'fa-kickstarter'       => ['class' => 'fa-kickstarter', 'name' => 'Kickstarter', 'code' => 'f3bb'],
    'fa-kickstarter-k'     => ['class' => 'fa-kickstarter-k', 'name' => 'Kickstarter k', 'code' => 'f3bc'],
    'fa-korvue'            => ['class' => 'fa-korvue', 'name' => 'Korvue', 'code' => 'f42f'],
    'fa-language'          => ['class' => 'fa-language', 'name' => 'Language', 'code' => 'f1ab'],
    'fa-laptop'            => ['class' => 'fa-laptop', 'name' => 'Laptop', 'code' => 'f109'],
    'fa-laravel'           => ['class' => 'fa-laravel', 'name' => 'Laravel', 'code' => 'f3bd'],
    'fa-lastfm'            => ['class' => 'fa-lastfm', 'name' => 'Lastfm', 'code' => 'f202'],
    'fa-lastfm-square'     => ['class' => 'fa-lastfm-square', 'name' => 'Lastfm square', 'code' => 'f203'],
    'fa-leaf'              => ['class' => 'fa-leaf', 'name' => 'Leaf', 'code' => 'f06c'],
    'fa-leanpub'           => ['class' => 'fa-leanpub', 'name' => 'Leanpub', 'code' => 'f212'],
    'fa-lemon'             => ['class' => 'fa-lemon', 'name' => 'Lemon', 'code' => 'f094'],
    'fa-less'              => ['class' => 'fa-less', 'name' => 'Less', 'code' => 'f41d'],
    'fa-level-down-alt'    => ['class' => 'fa-level-down-alt', 'name' => 'Level down alt', 'code' => 'f3be'],
    'fa-level-up-alt'      => ['class' => 'fa-level-up-alt', 'name' => 'Level up alt', 'code' => 'f3bf'],
    'fa-life-ring'         => ['class' => 'fa-life-ring', 'name' => 'Life ring', 'code' => 'f1cd'],
    'fa-lightbulb'         => ['class' => 'fa-lightbulb', 'name' => 'Lightbulb', 'code' => 'f0eb'],
    'fa-line'              => ['class' => 'fa-line', 'name' => 'Line', 'code' => 'f3c0'],
    'fa-link'              => ['class' => 'fa-link', 'name' => 'Link', 'code' => 'f0c1'],
    'fa-linkedin'          => ['class' => 'fa-linkedin', 'name' => 'Linkedin', 'code' => 'f08c'],
    'fa-linkedin-in'       => ['class' => 'fa-linkedin-in', 'name' => 'Linkedin in', 'code' => 'f0e1'],
    'fa-linode'            => ['class' => 'fa-linode', 'name' => 'Linode', 'code' => 'f2b8'],
    'fa-linux'             => ['class' => 'fa-linux', 'name' => 'Linux', 'code' => 'f17c'],
    'fa-lira-sign'         => ['class' => 'fa-lira-sign', 'name' => 'Lira sign', 'code' => 'f195'],
    'fa-list'              => ['class' => 'fa-list', 'name' => 'List', 'code' => 'f03a'],
    'fa-list-alt'          => ['class' => 'fa-list-alt', 'name' => 'List alt', 'code' => 'f022'],
    'fa-list-ol'           => ['class' => 'fa-list-ol', 'name' => 'List ol', 'code' => 'f0cb'],
    'fa-list-ul'           => ['class' => 'fa-list-ul', 'name' => 'List ul', 'code' => 'f0ca'],
    'fa-location-arrow'    => ['class' => 'fa-location-arrow', 'name' => 'Location arrow', 'code' => 'f124'],
    'fa-lock'              => ['class' => 'fa-lock', 'name' => 'Lock', 'code' => 'f023'],
    'fa-lock-open'         => ['class' => 'fa-lock-open', 'name' => 'Lock open', 'code' => 'f3c1'],
    'fa-long-arrow-alt-down' => ['class' => 'fa-long-arrow-alt-down', 'name' => 'Long arrow alt down', 'code' => 'f309'],
    'fa-long-arrow-alt-left' => ['class' => 'fa-long-arrow-alt-left', 'name' => 'Long arrow alt left', 'code' => 'f30a'],
    'fa-long-arrow-alt-right' => ['class' => 'fa-long-arrow-alt-right', 'name' => 'Long arrow alt right', 'code' => 'f30b'],
    'fa-long-arrow-alt-up' => ['class' => 'fa-long-arrow-alt-up', 'name' => 'Long arrow alt up', 'code' => 'f30c'],
    'fa-low-vision'        => ['class' => 'fa-low-vision', 'name' => 'Low vision', 'code' => 'f2a8'],
    'fa-lyft'              => ['class' => 'fa-lyft', 'name' => 'Lyft', 'code' => 'f3c3'],
    'fa-magento'           => ['class' => 'fa-magento', 'name' => 'Magento', 'code' => 'f3c4'],
    'fa-magic'             => ['class' => 'fa-magic', 'name' => 'Magic', 'code' => 'f0d0'],
    'fa-magnet'            => ['class' => 'fa-magnet', 'name' => 'Magnet', 'code' => 'f076'],
    'fa-male'              => ['class' => 'fa-male', 'name' => 'Male', 'code' => 'f183'],
    'fa-map'               => ['class' => 'fa-map', 'name' => 'Map', 'code' => 'f279'],
    'fa-map-marker'        => ['class' => 'fa-map-marker', 'name' => 'Map marker', 'code' => 'f041'],
    'fa-map-marker-alt'    => ['class' => 'fa-map-marker-alt', 'name' => 'Map marker alt', 'code' => 'f3c5'],
    'fa-map-pin'           => ['class' => 'fa-map-pin', 'name' => 'Map pin', 'code' => 'f276'],
    'fa-map-signs'         => ['class' => 'fa-map-signs', 'name' => 'Map signs', 'code' => 'f277'],
    'fa-mars'              => ['class' => 'fa-mars', 'name' => 'Mars', 'code' => 'f222'],
    'fa-mars-double'       => ['class' => 'fa-mars-double', 'name' => 'Mars double', 'code' => 'f227'],
    'fa-mars-stroke'       => ['class' => 'fa-mars-stroke', 'name' => 'Mars stroke', 'code' => 'f229'],
    'fa-mars-stroke-h'     => ['class' => 'fa-mars-stroke-h', 'name' => 'Mars stroke h', 'code' => 'f22b'],
    'fa-mars-stroke-v'     => ['class' => 'fa-mars-stroke-v', 'name' => 'Mars stroke v', 'code' => 'f22a'],
    'fa-maxcdn'            => ['class' => 'fa-maxcdn', 'name' => 'Maxcdn', 'code' => 'f136'],
    'fa-medapps'           => ['class' => 'fa-medapps', 'name' => 'Medapps', 'code' => 'f3c6'],
    'fa-medium'            => ['class' => 'fa-medium', 'name' => 'Medium', 'code' => 'f23a'],
    'fa-medium-m'          => ['class' => 'fa-medium-m', 'name' => 'Medium m', 'code' => 'f3c7'],
    'fa-medkit'            => ['class' => 'fa-medkit', 'name' => 'Medkit', 'code' => 'f0fa'],
    'fa-medrt'             => ['class' => 'fa-medrt', 'name' => 'Medrt', 'code' => 'f3c8'],
    'fa-meetup'            => ['class' => 'fa-meetup', 'name' => 'Meetup', 'code' => 'f2e0'],
    'fa-meh'               => ['class' => 'fa-meh', 'name' => 'Meh', 'code' => 'f11a'],
    'fa-mercury'           => ['class' => 'fa-mercury', 'name' => 'Mercury', 'code' => 'f223'],
    'fa-microchip'         => ['class' => 'fa-microchip', 'name' => 'Microchip', 'code' => 'f2db'],
    'fa-microphone'        => ['class' => 'fa-microphone', 'name' => 'Microphone', 'code' => 'f130'],
    'fa-microphone-slash'  => ['class' => 'fa-microphone-slash', 'name' => 'Microphone slash', 'code' => 'f131'],
    'fa-microsoft'         => ['class' => 'fa-microsoft', 'name' => 'Microsoft', 'code' => 'f3ca'],
    'fa-minus'             => ['class' => 'fa-minus', 'name' => 'Minus', 'code' => 'f068'],
    'fa-minus-circle'      => ['class' => 'fa-minus-circle', 'name' => 'Minus circle', 'code' => 'f056'],
    'fa-minus-square'      => ['class' => 'fa-minus-square', 'name' => 'Minus square', 'code' => 'f146'],
    'fa-mix'               => ['class' => 'fa-mix', 'name' => 'Mix', 'code' => 'f3cb'],
    'fa-mixcloud'          => ['class' => 'fa-mixcloud', 'name' => 'Mixcloud', 'code' => 'f289'],
    'fa-mizuni'            => ['class' => 'fa-mizuni', 'name' => 'Mizuni', 'code' => 'f3cc'],
    'fa-mobile'            => ['class' => 'fa-mobile', 'name' => 'Mobile', 'code' => 'f10b'],
    'fa-mobile-alt'        => ['class' => 'fa-mobile-alt', 'name' => 'Mobile alt', 'code' => 'f3cd'],
    'fa-modx'              => ['class' => 'fa-modx', 'name' => 'Modx', 'code' => 'f285'],
    'fa-monero'            => ['class' => 'fa-monero', 'name' => 'Monero', 'code' => 'f3d0'],
    'fa-money-bill-alt'    => ['class' => 'fa-money-bill-alt', 'name' => 'Money bill alt', 'code' => 'f3d1'],
    'fa-moon'              => ['class' => 'fa-moon', 'name' => 'Moon', 'code' => 'f186'],
    'fa-motorcycle'        => ['class' => 'fa-motorcycle', 'name' => 'Motorcycle', 'code' => 'f21c'],
    'fa-mouse-pointer'     => ['class' => 'fa-mouse-pointer', 'name' => 'Mouse pointer', 'code' => 'f245'],
    'fa-music'             => ['class' => 'fa-music', 'name' => 'Music', 'code' => 'f001'],
    'fa-napster'           => ['class' => 'fa-napster', 'name' => 'Napster', 'code' => 'f3d2'],
    'fa-neuter'            => ['class' => 'fa-neuter', 'name' => 'Neuter', 'code' => 'f22c'],
    'fa-newspaper'         => ['class' => 'fa-newspaper', 'name' => 'Newspaper', 'code' => 'f1ea'],
    'fa-nintendo-switch'   => ['class' => 'fa-nintendo-switch', 'name' => 'Nintendo switch', 'code' => 'f418'],
    'fa-node'              => ['class' => 'fa-node', 'name' => 'Node', 'code' => 'f419'],
    'fa-node-js'           => ['class' => 'fa-node-js', 'name' => 'Node js', 'code' => 'f3d3'],
    'fa-npm'               => ['class' => 'fa-npm', 'name' => 'Npm', 'code' => 'f3d4'],
    'fa-ns8'               => ['class' => 'fa-ns8', 'name' => 'Ns8', 'code' => 'f3d5'],
    'fa-nutritionix'       => ['class' => 'fa-nutritionix', 'name' => 'Nutritionix', 'code' => 'f3d6'],
    'fa-object-group'      => ['class' => 'fa-object-group', 'name' => 'Object group', 'code' => 'f247'],
    'fa-object-ungroup'    => ['class' => 'fa-object-ungroup', 'name' => 'Object ungroup', 'code' => 'f248'],
    'fa-odnoklassniki'     => ['class' => 'fa-odnoklassniki', 'name' => 'Odnoklassniki', 'code' => 'f263'],
    'fa-odnoklassniki-square' => ['class' => 'fa-odnoklassniki-square', 'name' => 'Odnoklassniki square', 'code' => 'f264'],
    'fa-opencart'          => ['class' => 'fa-opencart', 'name' => 'Opencart', 'code' => 'f23d'],
    'fa-openid'            => ['class' => 'fa-openid', 'name' => 'Openid', 'code' => 'f19b'],
    'fa-opera'             => ['class' => 'fa-opera', 'name' => 'Opera', 'code' => 'f26a'],
    'fa-optin-monster'     => ['class' => 'fa-optin-monster', 'name' => 'Optin monster', 'code' => 'f23c'],
    'fa-osi'               => ['class' => 'fa-osi', 'name' => 'Osi', 'code' => 'f41a'],
    'fa-outdent'           => ['class' => 'fa-outdent', 'name' => 'Outdent', 'code' => 'f03b'],
    'fa-page4'             => ['class' => 'fa-page4', 'name' => 'Page4', 'code' => 'f3d7'],
    'fa-pagelines'         => ['class' => 'fa-pagelines', 'name' => 'Pagelines', 'code' => 'f18c'],
    'fa-paint-brush'       => ['class' => 'fa-paint-brush', 'name' => 'Paint brush', 'code' => 'f1fc'],
    'fa-palfed'            => ['class' => 'fa-palfed', 'name' => 'Palfed', 'code' => 'f3d8'],
    'fa-pallet'            => ['class' => 'fa-pallet', 'name' => 'Pallet', 'code' => 'f482'],
    'fa-paper-plane'       => ['class' => 'fa-paper-plane', 'name' => 'Paper plane', 'code' => 'f1d8'],
    'fa-paperclip'         => ['class' => 'fa-paperclip', 'name' => 'Paperclip', 'code' => 'f0c6'],
    'fa-paragraph'         => ['class' => 'fa-paragraph', 'name' => 'Paragraph', 'code' => 'f1dd'],
    'fa-paste'             => ['class' => 'fa-paste', 'name' => 'Paste', 'code' => 'f0ea'],
    'fa-patreon'           => ['class' => 'fa-patreon', 'name' => 'Patreon', 'code' => 'f3d9'],
    'fa-pause'             => ['class' => 'fa-pause', 'name' => 'Pause', 'code' => 'f04c'],
    'fa-pause-circle'      => ['class' => 'fa-pause-circle', 'name' => 'Pause circle', 'code' => 'f28b'],
    'fa-paw'               => ['class' => 'fa-paw', 'name' => 'Paw', 'code' => 'f1b0'],
    'fa-paypal'            => ['class' => 'fa-paypal', 'name' => 'Paypal', 'code' => 'f1ed'],
    'fa-pen-square'        => ['class' => 'fa-pen-square', 'name' => 'Pen square', 'code' => 'f14b'],
    'fa-pencil-alt'        => ['class' => 'fa-pencil-alt', 'name' => 'Pencil alt', 'code' => 'f303'],
    'fa-percent'           => ['class' => 'fa-percent', 'name' => 'Percent', 'code' => 'f295'],
    'fa-periscope'         => ['class' => 'fa-periscope', 'name' => 'Periscope', 'code' => 'f3da'],
    'fa-phabricator'       => ['class' => 'fa-phabricator', 'name' => 'Phabricator', 'code' => 'f3db'],
    'fa-phoenix-framework' => ['class' => 'fa-phoenix-framework', 'name' => 'Phoenix framework', 'code' => 'f3dc'],
    'fa-phone'             => ['class' => 'fa-phone', 'name' => 'Phone', 'code' => 'f095'],
    'fa-phone-square'      => ['class' => 'fa-phone-square', 'name' => 'Phone square', 'code' => 'f098'],
    'fa-phone-volume'      => ['class' => 'fa-phone-volume', 'name' => 'Phone volume', 'code' => 'f2a0'],
    'fa-php'               => ['class' => 'fa-php', 'name' => 'Php', 'code' => 'f457'],
    'fa-pied-piper'        => ['class' => 'fa-pied-piper', 'name' => 'Pied piper', 'code' => 'f2ae'],
    'fa-pied-piper-alt'    => ['class' => 'fa-pied-piper-alt', 'name' => 'Pied piper alt', 'code' => 'f1a8'],
    'fa-pied-piper-pp'     => ['class' => 'fa-pied-piper-pp', 'name' => 'Pied piper pp', 'code' => 'f1a7'],
    'fa-pills'             => ['class' => 'fa-pills', 'name' => 'Pills', 'code' => 'f484'],
    'fa-pinterest'         => ['class' => 'fa-pinterest', 'name' => 'Pinterest', 'code' => 'f0d2'],
    'fa-pinterest-p'       => ['class' => 'fa-pinterest-p', 'name' => 'Pinterest p', 'code' => 'f231'],
    'fa-pinterest-square'  => ['class' => 'fa-pinterest-square', 'name' => 'Pinterest square', 'code' => 'f0d3'],
    'fa-plane'             => ['class' => 'fa-plane', 'name' => 'Plane', 'code' => 'f072'],
    'fa-play'              => ['class' => 'fa-play', 'name' => 'Play', 'code' => 'f04b'],
    'fa-play-circle'       => ['class' => 'fa-play-circle', 'name' => 'Play circle', 'code' => 'f144'],
    'fa-playstation'       => ['class' => 'fa-playstation', 'name' => 'Playstation', 'code' => 'f3df'],
    'fa-plug'              => ['class' => 'fa-plug', 'name' => 'Plug', 'code' => 'f1e6'],
    'fa-plus'              => ['class' => 'fa-plus', 'name' => 'Plus', 'code' => 'f067'],
    'fa-plus-circle'       => ['class' => 'fa-plus-circle', 'name' => 'Plus circle', 'code' => 'f055'],
    'fa-plus-square'       => ['class' => 'fa-plus-square', 'name' => 'Plus square', 'code' => 'f0fe'],
    'fa-podcast'           => ['class' => 'fa-podcast', 'name' => 'Podcast', 'code' => 'f2ce'],
    'fa-pound-sign'        => ['class' => 'fa-pound-sign', 'name' => 'Pound sign', 'code' => 'f154'],
    'fa-power-off'         => ['class' => 'fa-power-off', 'name' => 'Power off', 'code' => 'f011'],
    'fa-print'             => ['class' => 'fa-print', 'name' => 'Print', 'code' => 'f02f'],
    'fa-product-hunt'      => ['class' => 'fa-product-hunt', 'name' => 'Product hunt', 'code' => 'f288'],
    'fa-pushed'            => ['class' => 'fa-pushed', 'name' => 'Pushed', 'code' => 'f3e1'],
    'fa-puzzle-piece'      => ['class' => 'fa-puzzle-piece', 'name' => 'Puzzle piece', 'code' => 'f12e'],
    'fa-python'            => ['class' => 'fa-python', 'name' => 'Python', 'code' => 'f3e2'],
    'fa-qq'                => ['class' => 'fa-qq', 'name' => 'Qq', 'code' => 'f1d6'],
    'fa-qrcode'            => ['class' => 'fa-qrcode', 'name' => 'Qrcode', 'code' => 'f029'],
    'fa-question'          => ['class' => 'fa-question', 'name' => 'Question', 'code' => 'f128'],
    'fa-question-circle'   => ['class' => 'fa-question-circle', 'name' => 'Question circle', 'code' => 'f059'],
    'fa-quidditch'         => ['class' => 'fa-quidditch', 'name' => 'Quidditch', 'code' => 'f458'],
    'fa-quinscape'         => ['class' => 'fa-quinscape', 'name' => 'Quinscape', 'code' => 'f459'],
    'fa-quora'             => ['class' => 'fa-quora', 'name' => 'Quora', 'code' => 'f2c4'],
    'fa-quote-left'        => ['class' => 'fa-quote-left', 'name' => 'Quote left', 'code' => 'f10d'],
    'fa-quote-right'       => ['class' => 'fa-quote-right', 'name' => 'Quote right', 'code' => 'f10e'],
    'fa-random'            => ['class' => 'fa-random', 'name' => 'Random', 'code' => 'f074'],
    'fa-ravelry'           => ['class' => 'fa-ravelry', 'name' => 'Ravelry', 'code' => 'f2d9'],
    'fa-react'             => ['class' => 'fa-react', 'name' => 'React', 'code' => 'f41b'],
    'fa-rebel'             => ['class' => 'fa-rebel', 'name' => 'Rebel', 'code' => 'f1d0'],
    'fa-recycle'           => ['class' => 'fa-recycle', 'name' => 'Recycle', 'code' => 'f1b8'],
    'fa-red-river'         => ['class' => 'fa-red-river', 'name' => 'Red river', 'code' => 'f3e3'],
    'fa-reddit'            => ['class' => 'fa-reddit', 'name' => 'Reddit', 'code' => 'f1a1'],
    'fa-reddit-alien'      => ['class' => 'fa-reddit-alien', 'name' => 'Reddit alien', 'code' => 'f281'],
    'fa-reddit-square'     => ['class' => 'fa-reddit-square', 'name' => 'Reddit square', 'code' => 'f1a2'],
    'fa-redo'              => ['class' => 'fa-redo', 'name' => 'Redo', 'code' => 'f01e'],
    'fa-redo-alt'          => ['class' => 'fa-redo-alt', 'name' => 'Redo alt', 'code' => 'f2f9'],
    'fa-registered'        => ['class' => 'fa-registered', 'name' => 'Registered', 'code' => 'f25d'],
    'fa-rendact'           => ['class' => 'fa-rendact', 'name' => 'Rendact', 'code' => 'f3e4'],
    'fa-renren'            => ['class' => 'fa-renren', 'name' => 'Renren', 'code' => 'f18b'],
    'fa-reply'             => ['class' => 'fa-reply', 'name' => 'Reply', 'code' => 'f3e5'],
    'fa-reply-all'         => ['class' => 'fa-reply-all', 'name' => 'Reply all', 'code' => 'f122'],
    'fa-replyd'            => ['class' => 'fa-replyd', 'name' => 'Replyd', 'code' => 'f3e6'],
    'fa-resolving'         => ['class' => 'fa-resolving', 'name' => 'Resolving', 'code' => 'f3e7'],
    'fa-retweet'           => ['class' => 'fa-retweet', 'name' => 'Retweet', 'code' => 'f079'],
    'fa-road'              => ['class' => 'fa-road', 'name' => 'Road', 'code' => 'f018'],
    'fa-rocket'            => ['class' => 'fa-rocket', 'name' => 'Rocket', 'code' => 'f135'],
    'fa-rocketchat'        => ['class' => 'fa-rocketchat', 'name' => 'Rocketchat', 'code' => 'f3e8'],
    'fa-rockrms'           => ['class' => 'fa-rockrms', 'name' => 'Rockrms', 'code' => 'f3e9'],
    'fa-rss'               => ['class' => 'fa-rss', 'name' => 'Rss', 'code' => 'f09e'],
    'fa-rss-square'        => ['class' => 'fa-rss-square', 'name' => 'Rss square', 'code' => 'f143'],
    'fa-ruble-sign'        => ['class' => 'fa-ruble-sign', 'name' => 'Ruble sign', 'code' => 'f158'],
    'fa-rupee-sign'        => ['class' => 'fa-rupee-sign', 'name' => 'Rupee sign', 'code' => 'f156'],
    'fa-safari'            => ['class' => 'fa-safari', 'name' => 'Safari', 'code' => 'f267'],
    'fa-sass'              => ['class' => 'fa-sass', 'name' => 'Sass', 'code' => 'f41e'],
    'fa-save'              => ['class' => 'fa-save', 'name' => 'Save', 'code' => 'f0c7'],
    'fa-schlix'            => ['class' => 'fa-schlix', 'name' => 'Schlix', 'code' => 'f3ea'],
    'fa-scribd'            => ['class' => 'fa-scribd', 'name' => 'Scribd', 'code' => 'f28a'],
    'fa-search'            => ['class' => 'fa-search', 'name' => 'Search', 'code' => 'f002'],
    'fa-search-minus'      => ['class' => 'fa-search-minus', 'name' => 'Search minus', 'code' => 'f010'],
    'fa-search-plus'       => ['class' => 'fa-search-plus', 'name' => 'Search plus', 'code' => 'f00e'],
    'fa-searchengin'       => ['class' => 'fa-searchengin', 'name' => 'Searchengin', 'code' => 'f3eb'],
    'fa-sellcast'          => ['class' => 'fa-sellcast', 'name' => 'Sellcast', 'code' => 'f2da'],
    'fa-sellsy'            => ['class' => 'fa-sellsy', 'name' => 'Sellsy', 'code' => 'f213'],
    'fa-server'            => ['class' => 'fa-server', 'name' => 'Server', 'code' => 'f233'],
    'fa-servicestack'      => ['class' => 'fa-servicestack', 'name' => 'Servicestack', 'code' => 'f3ec'],
    'fa-share'             => ['class' => 'fa-share', 'name' => 'Share', 'code' => 'f064'],
    'fa-share-alt'         => ['class' => 'fa-share-alt', 'name' => 'Share alt', 'code' => 'f1e0'],
    'fa-share-alt-square'  => ['class' => 'fa-share-alt-square', 'name' => 'Share alt square', 'code' => 'f1e1'],
    'fa-share-square'      => ['class' => 'fa-share-square', 'name' => 'Share square', 'code' => 'f14d'],
    'fa-shekel-sign'       => ['class' => 'fa-shekel-sign', 'name' => 'Shekel sign', 'code' => 'f20b'],
    'fa-shield-alt'        => ['class' => 'fa-shield-alt', 'name' => 'Shield alt', 'code' => 'f3ed'],
    'fa-ship'              => ['class' => 'fa-ship', 'name' => 'Ship', 'code' => 'f21a'],
    'fa-shipping-fast'     => ['class' => 'fa-shipping-fast', 'name' => 'Shipping fast', 'code' => 'f48b'],
    'fa-shirtsinbulk'      => ['class' => 'fa-shirtsinbulk', 'name' => 'Shirtsinbulk', 'code' => 'f214'],
    'fa-shopping-bag'      => ['class' => 'fa-shopping-bag', 'name' => 'Shopping bag', 'code' => 'f290'],
    'fa-shopping-basket'   => ['class' => 'fa-shopping-basket', 'name' => 'Shopping basket', 'code' => 'f291'],
    'fa-shopping-cart'     => ['class' => 'fa-shopping-cart', 'name' => 'Shopping cart', 'code' => 'f07a'],
    'fa-shower'            => ['class' => 'fa-shower', 'name' => 'Shower', 'code' => 'f2cc'],
    'fa-sign-in-alt'       => ['class' => 'fa-sign-in-alt', 'name' => 'Sign in alt', 'code' => 'f2f6'],
    'fa-sign-language'     => ['class' => 'fa-sign-language', 'name' => 'Sign language', 'code' => 'f2a7'],
    'fa-sign-out-alt'      => ['class' => 'fa-sign-out-alt', 'name' => 'Sign out alt', 'code' => 'f2f5'],
    'fa-signal'            => ['class' => 'fa-signal', 'name' => 'Signal', 'code' => 'f012'],
    'fa-simplybuilt'       => ['class' => 'fa-simplybuilt', 'name' => 'Simplybuilt', 'code' => 'f215'],
    'fa-sistrix'           => ['class' => 'fa-sistrix', 'name' => 'Sistrix', 'code' => 'f3ee'],
    'fa-sitemap'           => ['class' => 'fa-sitemap', 'name' => 'Sitemap', 'code' => 'f0e8'],
    'fa-skyatlas'          => ['class' => 'fa-skyatlas', 'name' => 'Skyatlas', 'code' => 'f216'],
    'fa-skype'             => ['class' => 'fa-skype', 'name' => 'Skype', 'code' => 'f17e'],
    'fa-slack'             => ['class' => 'fa-slack', 'name' => 'Slack', 'code' => 'f198'],
    'fa-slack-hash'        => ['class' => 'fa-slack-hash', 'name' => 'Slack hash', 'code' => 'f3ef'],
    'fa-sliders-h'         => ['class' => 'fa-sliders-h', 'name' => 'Sliders h', 'code' => 'f1de'],
    'fa-slideshare'        => ['class' => 'fa-slideshare', 'name' => 'Slideshare', 'code' => 'f1e7'],
    'fa-smile'             => ['class' => 'fa-smile', 'name' => 'Smile', 'code' => 'f118'],
    'fa-snapchat'          => ['class' => 'fa-snapchat', 'name' => 'Snapchat', 'code' => 'f2ab'],
    'fa-snapchat-ghost'    => ['class' => 'fa-snapchat-ghost', 'name' => 'Snapchat ghost', 'code' => 'f2ac'],
    'fa-snapchat-square'   => ['class' => 'fa-snapchat-square', 'name' => 'Snapchat square', 'code' => 'f2ad'],
    'fa-snowflake'         => ['class' => 'fa-snowflake', 'name' => 'Snowflake', 'code' => 'f2dc'],
    'fa-sort'              => ['class' => 'fa-sort', 'name' => 'Sort', 'code' => 'f0dc'],
    'fa-sort-alpha-down'   => ['class' => 'fa-sort-alpha-down', 'name' => 'Sort alpha down', 'code' => 'f15d'],
    'fa-sort-alpha-up'     => ['class' => 'fa-sort-alpha-up', 'name' => 'Sort alpha up', 'code' => 'f15e'],
    'fa-sort-amount-down'  => ['class' => 'fa-sort-amount-down', 'name' => 'Sort amount down', 'code' => 'f160'],
    'fa-sort-amount-up'    => ['class' => 'fa-sort-amount-up', 'name' => 'Sort amount up', 'code' => 'f161'],
    'fa-sort-down'         => ['class' => 'fa-sort-down', 'name' => 'Sort down', 'code' => 'f0dd'],
    'fa-sort-numeric-down' => ['class' => 'fa-sort-numeric-down', 'name' => 'Sort numeric down', 'code' => 'f162'],
    'fa-sort-numeric-up'   => ['class' => 'fa-sort-numeric-up', 'name' => 'Sort numeric up', 'code' => 'f163'],
    'fa-sort-up'           => ['class' => 'fa-sort-up', 'name' => 'Sort up', 'code' => 'f0de'],
    'fa-soundcloud'        => ['class' => 'fa-soundcloud', 'name' => 'Soundcloud', 'code' => 'f1be'],
    'fa-space-shuttle'     => ['class' => 'fa-space-shuttle', 'name' => 'Space shuttle', 'code' => 'f197'],
    'fa-speakap'           => ['class' => 'fa-speakap', 'name' => 'Speakap', 'code' => 'f3f3'],
    'fa-spinner'           => ['class' => 'fa-spinner', 'name' => 'Spinner', 'code' => 'f110'],
    'fa-spotify'           => ['class' => 'fa-spotify', 'name' => 'Spotify', 'code' => 'f1bc'],
    'fa-square'            => ['class' => 'fa-square', 'name' => 'Square', 'code' => 'f0c8'],
    'fa-square-full'       => ['class' => 'fa-square-full', 'name' => 'Square full', 'code' => 'f45c'],
    'fa-stack-exchange'    => ['class' => 'fa-stack-exchange', 'name' => 'Stack exchange', 'code' => 'f18d'],
    'fa-stack-overflow'    => ['class' => 'fa-stack-overflow', 'name' => 'Stack overflow', 'code' => 'f16c'],
    'fa-star'              => ['class' => 'fa-star', 'name' => 'Star', 'code' => 'f005'],
    'fa-star-half'         => ['class' => 'fa-star-half', 'name' => 'Star half', 'code' => 'f089'],
    'fa-staylinked'        => ['class' => 'fa-staylinked', 'name' => 'Staylinked', 'code' => 'f3f5'],
    'fa-steam'             => ['class' => 'fa-steam', 'name' => 'Steam', 'code' => 'f1b6'],
    'fa-steam-square'      => ['class' => 'fa-steam-square', 'name' => 'Steam square', 'code' => 'f1b7'],
    'fa-steam-symbol'      => ['class' => 'fa-steam-symbol', 'name' => 'Steam symbol', 'code' => 'f3f6'],
    'fa-step-backward'     => ['class' => 'fa-step-backward', 'name' => 'Step backward', 'code' => 'f048'],
    'fa-step-forward'      => ['class' => 'fa-step-forward', 'name' => 'Step forward', 'code' => 'f051'],
    'fa-stethoscope'       => ['class' => 'fa-stethoscope', 'name' => 'Stethoscope', 'code' => 'f0f1'],
    'fa-sticker-mule'      => ['class' => 'fa-sticker-mule', 'name' => 'Sticker mule', 'code' => 'f3f7'],
    'fa-sticky-note'       => ['class' => 'fa-sticky-note', 'name' => 'Sticky note', 'code' => 'f249'],
    'fa-stop'              => ['class' => 'fa-stop', 'name' => 'Stop', 'code' => 'f04d'],
    'fa-stop-circle'       => ['class' => 'fa-stop-circle', 'name' => 'Stop circle', 'code' => 'f28d'],
    'fa-stopwatch'         => ['class' => 'fa-stopwatch', 'name' => 'Stopwatch', 'code' => 'f2f2'],
    'fa-strava'            => ['class' => 'fa-strava', 'name' => 'Strava', 'code' => 'f428'],
    'fa-street-view'       => ['class' => 'fa-street-view', 'name' => 'Street view', 'code' => 'f21d'],
    'fa-strikethrough'     => ['class' => 'fa-strikethrough', 'name' => 'Strikethrough', 'code' => 'f0cc'],
    'fa-stripe'            => ['class' => 'fa-stripe', 'name' => 'Stripe', 'code' => 'f429'],
    'fa-stripe-s'          => ['class' => 'fa-stripe-s', 'name' => 'Stripe s', 'code' => 'f42a'],
    'fa-studiovinari'      => ['class' => 'fa-studiovinari', 'name' => 'Studiovinari', 'code' => 'f3f8'],
    'fa-stumbleupon'       => ['class' => 'fa-stumbleupon', 'name' => 'Stumbleupon', 'code' => 'f1a4'],
    'fa-stumbleupon-circle' => ['class' => 'fa-stumbleupon-circle', 'name' => 'Stumbleupon circle', 'code' => 'f1a3'],
    'fa-subscript'         => ['class' => 'fa-subscript', 'name' => 'Subscript', 'code' => 'f12c'],
    'fa-subway'            => ['class' => 'fa-subway', 'name' => 'Subway', 'code' => 'f239'],
    'fa-suitcase'          => ['class' => 'fa-suitcase', 'name' => 'Suitcase', 'code' => 'f0f2'],
    'fa-sun'               => ['class' => 'fa-sun', 'name' => 'Sun', 'code' => 'f185'],
    'fa-superpowers'       => ['class' => 'fa-superpowers', 'name' => 'Superpowers', 'code' => 'f2dd'],
    'fa-superscript'       => ['class' => 'fa-superscript', 'name' => 'Superscript', 'code' => 'f12b'],
    'fa-supple'            => ['class' => 'fa-supple', 'name' => 'Supple', 'code' => 'f3f9'],
    'fa-sync'              => ['class' => 'fa-sync', 'name' => 'Sync', 'code' => 'f021'],
    'fa-sync-alt'          => ['class' => 'fa-sync-alt', 'name' => 'Sync alt', 'code' => 'f2f1'],
    'fa-syringe'           => ['class' => 'fa-syringe', 'name' => 'Syringe', 'code' => 'f48e'],
    'fa-table'             => ['class' => 'fa-table', 'name' => 'Table', 'code' => 'f0ce'],
    'fa-table-tennis'      => ['class' => 'fa-table-tennis', 'name' => 'Table tennis', 'code' => 'f45d'],
    'fa-tablet'            => ['class' => 'fa-tablet', 'name' => 'Tablet', 'code' => 'f10a'],
    'fa-tablet-alt'        => ['class' => 'fa-tablet-alt', 'name' => 'Tablet alt', 'code' => 'f3fa'],
    'fa-tachometer-alt'    => ['class' => 'fa-tachometer-alt', 'name' => 'Tachometer alt', 'code' => 'f3fd'],
    'fa-tag'               => ['class' => 'fa-tag', 'name' => 'Tag', 'code' => 'f02b'],
    'fa-tags'              => ['class' => 'fa-tags', 'name' => 'Tags', 'code' => 'f02c'],
    'fa-tasks'             => ['class' => 'fa-tasks', 'name' => 'Tasks', 'code' => 'f0ae'],
    'fa-taxi'              => ['class' => 'fa-taxi', 'name' => 'Taxi', 'code' => 'f1ba'],
    'fa-telegram'          => ['class' => 'fa-telegram', 'name' => 'Telegram', 'code' => 'f2c6'],
    'fa-telegram-plane'    => ['class' => 'fa-telegram-plane', 'name' => 'Telegram plane', 'code' => 'f3fe'],
    'fa-tencent-weibo'     => ['class' => 'fa-tencent-weibo', 'name' => 'Tencent weibo', 'code' => 'f1d5'],
    'fa-terminal'          => ['class' => 'fa-terminal', 'name' => 'Terminal', 'code' => 'f120'],
    'fa-text-height'       => ['class' => 'fa-text-height', 'name' => 'Text height', 'code' => 'f034'],
    'fa-text-width'        => ['class' => 'fa-text-width', 'name' => 'Text width', 'code' => 'f035'],
    'fa-th'                => ['class' => 'fa-th', 'name' => 'Th', 'code' => 'f00a'],
    'fa-th-large'          => ['class' => 'fa-th-large', 'name' => 'Th large', 'code' => 'f009'],
    'fa-th-list'           => ['class' => 'fa-th-list', 'name' => 'Th list', 'code' => 'f00b'],
    'fa-themeisle'         => ['class' => 'fa-themeisle', 'name' => 'Themeisle', 'code' => 'f2b2'],
    'fa-thermometer'       => ['class' => 'fa-thermometer', 'name' => 'Thermometer', 'code' => 'f491'],
    'fa-thermometer-empty' => ['class' => 'fa-thermometer-empty', 'name' => 'Thermometer empty', 'code' => 'f2cb'],
    'fa-thermometer-full'  => ['class' => 'fa-thermometer-full', 'name' => 'Thermometer full', 'code' => 'f2c7'],
    'fa-thermometer-half'  => ['class' => 'fa-thermometer-half', 'name' => 'Thermometer half', 'code' => 'f2c9'],
    'fa-thermometer-quarter' => ['class' => 'fa-thermometer-quarter', 'name' => 'Thermometer quarter', 'code' => 'f2ca'],
    'fa-thermometer-three-quarters' => ['class' => 'fa-thermometer-three-quarters', 'name' => 'Thermometer three quarters', 'code' => 'f2c8'],
    'fa-thumbs-down'       => ['class' => 'fa-thumbs-down', 'name' => 'Thumbs down', 'code' => 'f165'],
    'fa-thumbs-up'         => ['class' => 'fa-thumbs-up', 'name' => 'Thumbs up', 'code' => 'f164'],
    'fa-thumbtack'         => ['class' => 'fa-thumbtack', 'name' => 'Thumbtack', 'code' => 'f08d'],
    'fa-ticket-alt'        => ['class' => 'fa-ticket-alt', 'name' => 'Ticket alt', 'code' => 'f3ff'],
    'fa-times'             => ['class' => 'fa-times', 'name' => 'Times', 'code' => 'f00d'],
    'fa-times-circle'      => ['class' => 'fa-times-circle', 'name' => 'Times circle', 'code' => 'f057'],
    'fa-tint'              => ['class' => 'fa-tint', 'name' => 'Tint', 'code' => 'f043'],
    'fa-toggle-off'        => ['class' => 'fa-toggle-off', 'name' => 'Toggle off', 'code' => 'f204'],
    'fa-toggle-on'         => ['class' => 'fa-toggle-on', 'name' => 'Toggle on', 'code' => 'f205'],
    'fa-trademark'         => ['class' => 'fa-trademark', 'name' => 'Trademark', 'code' => 'f25c'],
    'fa-train'             => ['class' => 'fa-train', 'name' => 'Train', 'code' => 'f238'],
    'fa-transgender'       => ['class' => 'fa-transgender', 'name' => 'Transgender', 'code' => 'f224'],
    'fa-transgender-alt'   => ['class' => 'fa-transgender-alt', 'name' => 'Transgender alt', 'code' => 'f225'],
    'fa-trash'             => ['class' => 'fa-trash', 'name' => 'Trash', 'code' => 'f1f8'],
    'fa-trash-alt'         => ['class' => 'fa-trash-alt', 'name' => 'Trash alt', 'code' => 'f2ed'],
    'fa-tree'              => ['class' => 'fa-tree', 'name' => 'Tree', 'code' => 'f1bb'],
    'fa-trello'            => ['class' => 'fa-trello', 'name' => 'Trello', 'code' => 'f181'],
    'fa-tripadvisor'       => ['class' => 'fa-tripadvisor', 'name' => 'Tripadvisor', 'code' => 'f262'],
    'fa-trophy'            => ['class' => 'fa-trophy', 'name' => 'Trophy', 'code' => 'f091'],
    'fa-truck'             => ['class' => 'fa-truck', 'name' => 'Truck', 'code' => 'f0d1'],
    'fa-tty'               => ['class' => 'fa-tty', 'name' => 'Tty', 'code' => 'f1e4'],
    'fa-tumblr'            => ['class' => 'fa-tumblr', 'name' => 'Tumblr', 'code' => 'f173'],
    'fa-tumblr-square'     => ['class' => 'fa-tumblr-square', 'name' => 'Tumblr square', 'code' => 'f174'],
    'fa-tv'                => ['class' => 'fa-tv', 'name' => 'Tv', 'code' => 'f26c'],
    'fa-twitch'            => ['class' => 'fa-twitch', 'name' => 'Twitch', 'code' => 'f1e8'],
    'fa-twitter'           => ['class' => 'fa-twitter', 'name' => 'Twitter', 'code' => 'f099'],
    'fa-twitter-square'    => ['class' => 'fa-twitter-square', 'name' => 'Twitter square', 'code' => 'f081'],
    'fa-typo3'             => ['class' => 'fa-typo3', 'name' => 'Typo3', 'code' => 'f42b'],
    'fa-uber'              => ['class' => 'fa-uber', 'name' => 'Uber', 'code' => 'f402'],
    'fa-uikit'             => ['class' => 'fa-uikit', 'name' => 'Uikit', 'code' => 'f403'],
    'fa-umbrella'          => ['class' => 'fa-umbrella', 'name' => 'Umbrella', 'code' => 'f0e9'],
    'fa-underline'         => ['class' => 'fa-underline', 'name' => 'Underline', 'code' => 'f0cd'],
    'fa-undo'              => ['class' => 'fa-undo', 'name' => 'Undo', 'code' => 'f0e2'],
    'fa-undo-alt'          => ['class' => 'fa-undo-alt', 'name' => 'Undo alt', 'code' => 'f2ea'],
    'fa-uniregistry'       => ['class' => 'fa-uniregistry', 'name' => 'Uniregistry', 'code' => 'f404'],
    'fa-universal-access'  => ['class' => 'fa-universal-access', 'name' => 'Universal access', 'code' => 'f29a'],
    'fa-university'        => ['class' => 'fa-university', 'name' => 'University', 'code' => 'f19c'],
    'fa-unlink'            => ['class' => 'fa-unlink', 'name' => 'Unlink', 'code' => 'f127'],
    'fa-unlock'            => ['class' => 'fa-unlock', 'name' => 'Unlock', 'code' => 'f09c'],
    'fa-unlock-alt'        => ['class' => 'fa-unlock-alt', 'name' => 'Unlock alt', 'code' => 'f13e'],
    'fa-untappd'           => ['class' => 'fa-untappd', 'name' => 'Untappd', 'code' => 'f405'],
    'fa-upload'            => ['class' => 'fa-upload', 'name' => 'Upload', 'code' => 'f093'],
    'fa-usb'               => ['class' => 'fa-usb', 'name' => 'Usb', 'code' => 'f287'],
    'fa-user'              => ['class' => 'fa-user', 'name' => 'User', 'code' => 'f007'],
    'fa-user-circle'       => ['class' => 'fa-user-circle', 'name' => 'User circle', 'code' => 'f2bd'],
    'fa-user-md'           => ['class' => 'fa-user-md', 'name' => 'User md', 'code' => 'f0f0'],
    'fa-user-plus'         => ['class' => 'fa-user-plus', 'name' => 'User plus', 'code' => 'f234'],
    'fa-user-secret'       => ['class' => 'fa-user-secret', 'name' => 'User secret', 'code' => 'f21b'],
    'fa-user-times'        => ['class' => 'fa-user-times', 'name' => 'User times', 'code' => 'f235'],
    'fa-users'             => ['class' => 'fa-users', 'name' => 'Users', 'code' => 'f0c0'],
    'fa-ussunnah'          => ['class' => 'fa-ussunnah', 'name' => 'Ussunnah', 'code' => 'f407'],
    'fa-utensil-spoon'     => ['class' => 'fa-utensil-spoon', 'name' => 'Utensil spoon', 'code' => 'f2e5'],
    'fa-utensils'          => ['class' => 'fa-utensils', 'name' => 'Utensils', 'code' => 'f2e7'],
    'fa-vaadin'            => ['class' => 'fa-vaadin', 'name' => 'Vaadin', 'code' => 'f408'],
    'fa-venus'             => ['class' => 'fa-venus', 'name' => 'Venus', 'code' => 'f221'],
    'fa-venus-double'      => ['class' => 'fa-venus-double', 'name' => 'Venus double', 'code' => 'f226'],
    'fa-venus-mars'        => ['class' => 'fa-venus-mars', 'name' => 'Venus mars', 'code' => 'f228'],
    'fa-viacoin'           => ['class' => 'fa-viacoin', 'name' => 'Viacoin', 'code' => 'f237'],
    'fa-viadeo'            => ['class' => 'fa-viadeo', 'name' => 'Viadeo', 'code' => 'f2a9'],
    'fa-viadeo-square'     => ['class' => 'fa-viadeo-square', 'name' => 'Viadeo square', 'code' => 'f2aa'],
    'fa-viber'             => ['class' => 'fa-viber', 'name' => 'Viber', 'code' => 'f409'],
    'fa-video'             => ['class' => 'fa-video', 'name' => 'Video', 'code' => 'f03d'],
    'fa-vimeo'             => ['class' => 'fa-vimeo', 'name' => 'Vimeo', 'code' => 'f40a'],
    'fa-vimeo-square'      => ['class' => 'fa-vimeo-square', 'name' => 'Vimeo square', 'code' => 'f194'],
    'fa-vimeo-v'           => ['class' => 'fa-vimeo-v', 'name' => 'Vimeo v', 'code' => 'f27d'],
    'fa-vine'              => ['class' => 'fa-vine', 'name' => 'Vine', 'code' => 'f1ca'],
    'fa-vk'                => ['class' => 'fa-vk', 'name' => 'Vk', 'code' => 'f189'],
    'fa-vnv'               => ['class' => 'fa-vnv', 'name' => 'Vnv', 'code' => 'f40b'],
    'fa-volleyball-ball'   => ['class' => 'fa-volleyball-ball', 'name' => 'Volleyball ball', 'code' => 'f45f'],
    'fa-volume-down'       => ['class' => 'fa-volume-down', 'name' => 'Volume down', 'code' => 'f027'],
    'fa-volume-off'        => ['class' => 'fa-volume-off', 'name' => 'Volume off', 'code' => 'f026'],
    'fa-volume-up'         => ['class' => 'fa-volume-up', 'name' => 'Volume up', 'code' => 'f028'],
    'fa-vuejs'             => ['class' => 'fa-vuejs', 'name' => 'Vuejs', 'code' => 'f41f'],
    'fa-warehouse'         => ['class' => 'fa-warehouse', 'name' => 'Warehouse', 'code' => 'f494'],
    'fa-weibo'             => ['class' => 'fa-weibo', 'name' => 'Weibo', 'code' => 'f18a'],
    'fa-weight'            => ['class' => 'fa-weight', 'name' => 'Weight', 'code' => 'f496'],
    'fa-weixin'            => ['class' => 'fa-weixin', 'name' => 'Weixin', 'code' => 'f1d7'],
    'fa-whatsapp'          => ['class' => 'fa-whatsapp', 'name' => 'Whatsapp', 'code' => 'f232'],
    'fa-whatsapp-square'   => ['class' => 'fa-whatsapp-square', 'name' => 'Whatsapp square', 'code' => 'f40c'],
    'fa-wheelchair'        => ['class' => 'fa-wheelchair', 'name' => 'Wheelchair', 'code' => 'f193'],
    'fa-whmcs'             => ['class' => 'fa-whmcs', 'name' => 'Whmcs', 'code' => 'f40d'],
    'fa-wifi'              => ['class' => 'fa-wifi', 'name' => 'Wifi', 'code' => 'f1eb'],
    'fa-wikipedia-w'       => ['class' => 'fa-wikipedia-w', 'name' => 'Wikipedia w', 'code' => 'f266'],
    'fa-window-close'      => ['class' => 'fa-window-close', 'name' => 'Window close', 'code' => 'f410'],
    'fa-window-maximize'   => ['class' => 'fa-window-maximize', 'name' => 'Window maximize', 'code' => 'f2d0'],
    'fa-window-minimize'   => ['class' => 'fa-window-minimize', 'name' => 'Window minimize', 'code' => 'f2d1'],
    'fa-window-restore'    => ['class' => 'fa-window-restore', 'name' => 'Window restore', 'code' => 'f2d2'],
    'fa-windows'           => ['class' => 'fa-windows', 'name' => 'Windows', 'code' => 'f17a'],
    'fa-won-sign'          => ['class' => 'fa-won-sign', 'name' => 'Won sign', 'code' => 'f159'],
    'fa-wordpress'         => ['class' => 'fa-wordpress', 'name' => 'Wordpress', 'code' => 'f19a'],
    'fa-wordpress-simple'  => ['class' => 'fa-wordpress-simple', 'name' => 'Wordpress simple', 'code' => 'f411'],
    'fa-wpbeginner'        => ['class' => 'fa-wpbeginner', 'name' => 'Wpbeginner', 'code' => 'f297'],
    'fa-wpexplorer'        => ['class' => 'fa-wpexplorer', 'name' => 'Wpexplorer', 'code' => 'f2de'],
    'fa-wpforms'           => ['class' => 'fa-wpforms', 'name' => 'Wpforms', 'code' => 'f298'],
    'fa-wrench'            => ['class' => 'fa-wrench', 'name' => 'Wrench', 'code' => 'f0ad'],
    'fa-xbox'              => ['class' => 'fa-xbox', 'name' => 'Xbox', 'code' => 'f412'],
    'fa-xing'              => ['class' => 'fa-xing', 'name' => 'Xing', 'code' => 'f168'],
    'fa-xing-square'       => ['class' => 'fa-xing-square', 'name' => 'Xing square', 'code' => 'f169'],
    'fa-y-combinator'      => ['class' => 'fa-y-combinator', 'name' => 'Y combinator', 'code' => 'f23b'],
    'fa-yahoo'             => ['class' => 'fa-yahoo', 'name' => 'Yahoo', 'code' => 'f19e'],
    'fa-yandex'            => ['class' => 'fa-yandex', 'name' => 'Yandex', 'code' => 'f413'],
    'fa-yandex-international' => ['class' => 'fa-yandex-international', 'name' => 'Yandex international', 'code' => 'f414'],
    'fa-yelp'              => ['class' => 'fa-yelp', 'name' => 'Yelp', 'code' => 'f1e9'],
    'fa-yen-sign'          => ['class' => 'fa-yen-sign', 'name' => 'Yen sign', 'code' => 'f157'],
    'fa-yoast'             => ['class' => 'fa-yoast', 'name' => 'Yoast', 'code' => 'f2b1'],
    'fa-youtube'           => ['class' => 'fa-youtube', 'name' => 'Youtube', 'code' => 'f167'],
    'fa-youtube-square'    => ['class' => 'fa-youtube-square', 'name' => 'Youtube square', 'code' => 'f431']
];
?>